import { adminMembership, audit, integrationStatus, json, paypalAccessToken, paypalBaseUrl, portalEnv, randomId, requireAdmin, requireAdminRole } from "@/app/portal/server";

type ActionBody = { action?: unknown; id?: unknown; email?: unknown; role?: unknown; title?: unknown; description?: unknown; priority?: unknown; dueAt?: unknown; status?: unknown; paymentId?: unknown; amountMinor?: unknown; reason?: unknown; applicationId?: unknown; externalReference?: unknown; adminNote?: unknown };

const roles = ["superadmin", "reviewer", "caseworker", "finance", "support"];
const safeText = (value: unknown, max = 500) => typeof value === "string" ? value.trim().slice(0, max) : "";

export async function GET(request: Request) {
  const session = await requireAdmin(request); if (session.error || !session.user) return session.error!;
  const url = new URL(request.url); let paypalDiagnostic: { configured: boolean; mode: string; authenticated: boolean; error?: string } | null = null;
  if (url.searchParams.get("diagnostics") === "1") {
    const configured = integrationStatus().paypal; paypalDiagnostic = { configured, mode: portalEnv.PAYPAL_MODE === "sandbox" ? "sandbox" : "live", authenticated: false };
    if (configured) try { await paypalAccessToken(); paypalDiagnostic.authenticated = true; } catch (error) { paypalDiagnostic.error = error instanceof Error ? error.message.slice(0, 180) : "PayPal authentication failed."; }
    await audit("integration_diagnostic_run", "integration", "paypal", session.user.id, { authenticated: paypalDiagnostic.authenticated, mode: paypalDiagnostic.mode });
  }
  const [tasks, refunds, privacy, feedback, handoffs, emails, security, staff, funnel] = await Promise.all([
    portalEnv.DB.prepare(`SELECT t.id,t.title,t.description,t.priority,t.status,t.due_at AS dueAt,t.created_at AS createdAt,a.public_id AS applicationPublicId,u.email AS assignedTo FROM admin_tasks t LEFT JOIN applications a ON a.id=t.application_id LEFT JOIN admins ad ON ad.id=t.assigned_admin_id LEFT JOIN users u ON u.id=ad.user_id ORDER BY CASE t.status WHEN 'open' THEN 0 ELSE 1 END,coalesce(t.due_at,9999999999999),t.created_at DESC LIMIT 100`).all(),
    portalEnv.DB.prepare(`SELECT r.id,r.amount_minor AS amountMinor,r.reason,r.status,r.provider_reference AS providerReference,r.created_at AS createdAt,p.id AS paymentId,p.provider,p.currency,p.amount_minor AS paymentAmount,u.email FROM payment_refunds r JOIN payments p ON p.id=r.payment_id JOIN users u ON u.id=p.user_id ORDER BY r.created_at DESC LIMIT 100`).all(),
    portalEnv.DB.prepare(`SELECT d.id,d.request_type AS requestType,d.status,d.admin_note AS adminNote,d.requested_at AS requestedAt,d.completed_at AS completedAt,u.email FROM user_data_requests d JOIN users u ON u.id=d.user_id ORDER BY CASE d.status WHEN 'requested' THEN 0 WHEN 'processing' THEN 1 ELSE 2 END,d.requested_at DESC LIMIT 100`).all(),
    portalEnv.DB.prepare(`SELECT f.id,f.stage,f.rating,f.comment,f.created_at AS createdAt,u.email,a.public_id AS applicationPublicId FROM service_feedback f JOIN users u ON u.id=f.user_id JOIN applications a ON a.id=f.application_id ORDER BY f.created_at DESC LIMIT 100`).all(),
    portalEnv.DB.prepare(`SELECT h.id,h.provider,h.external_reference AS externalReference,h.status,h.attempts,h.last_error AS lastError,h.created_at AS createdAt,a.public_id AS applicationPublicId FROM integration_handoffs h JOIN applications a ON a.id=h.application_id ORDER BY h.updated_at DESC LIMIT 100`).all(),
    portalEnv.DB.prepare(`SELECT e.id,e.category,e.recipient,e.subject,e.status,e.attempts,e.last_error AS lastError,e.created_at AS createdAt,a.public_id AS applicationPublicId FROM email_deliveries e LEFT JOIN applications a ON a.id=e.application_id WHERE e.status='failed' ORDER BY e.created_at DESC LIMIT 100`).all(),
    portalEnv.DB.prepare(`SELECT s.id,s.event,s.detail_json AS detailJson,s.created_at AS createdAt,u.email FROM security_events s LEFT JOIN users u ON u.id=s.user_id ORDER BY s.created_at DESC LIMIT 100`).all(),
    portalEnv.DB.prepare(`SELECT a.id,a.role,a.status,a.last_login_at AS lastLoginAt,a.created_at AS createdAt,u.email FROM admins a JOIN users u ON u.id=a.user_id ORDER BY u.email`).all(),
    portalEnv.DB.prepare(`SELECT (SELECT COUNT(*) FROM users) AS accounts,(SELECT COUNT(*) FROM payments WHERE status='paid') AS paid,(SELECT COUNT(*) FROM applications WHERE status='submitted') AS submitted,(SELECT COUNT(*) FROM applications WHERE review_status='completed') AS completed,(SELECT COUNT(*) FROM appointment_requests WHERE status IN ('confirmed','completed')) AS calls`).first(),
  ]);
  return json({ integrations: integrationStatus(), paypalDiagnostic, tasks: tasks.results, refunds: refunds.results, privacy: privacy.results, feedback: feedback.results, handoffs: handoffs.results, failedEmails: emails.results, security: security.results, staff: staff.results, funnel });
}

export async function POST(request: Request) {
  const session = await requireAdmin(request); if (session.error || !session.user) return session.error!; const body = await request.json() as ActionBody; const action = safeText(body.action, 60); const now = Date.now();
  if (action === "staff_invite" || action === "staff_update") {
    const roleSession = await requireAdminRole(request, ["superadmin"]); if (roleSession.error || !roleSession.user || !roleSession.membership) return roleSession.error!;
    const role = safeText(body.role, 30); if (!roles.includes(role)) return json({ error: "Choose a valid staff role." }, 400);
    if (action === "staff_invite") { const email = safeText(body.email, 254).toLowerCase(); const user = await portalEnv.DB.prepare("SELECT id FROM users WHERE email=? LIMIT 1").bind(email).first<{ id: string }>(); if (!user) return json({ error: "The staff member must first create a verified portal account with this email." }, 409); await portalEnv.DB.prepare("INSERT INTO admins (id,user_id,role,status,invited_by,created_at) VALUES (?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET role=excluded.role,status='active',invited_by=excluded.invited_by").bind(randomId("adm_"), user.id, role, "active", roleSession.membership.id, now).run(); await audit("admin_staff_invited", "user", user.id, session.user.id, { email, role }); return json({ ok: true }); }
    const id = safeText(body.id, 100); const status = safeText(body.status, 20) === "suspended" ? "suspended" : "active"; await portalEnv.DB.prepare("UPDATE admins SET role=?,status=? WHERE id=?").bind(role, status, id).run(); await audit("admin_staff_updated", "admin", id, session.user.id, { role, status }); return json({ ok: true });
  }
  if (action === "task_create" || action === "task_update") {
    const membership = await adminMembership(session.user.id); if (!membership) return json({ error: "Administrator access required." }, 403);
    if (action === "task_create") { const title = safeText(body.title, 180); if (!title) return json({ error: "Add a task title." }, 400); const applicationId = safeText(body.applicationId, 100) || null; await portalEnv.DB.prepare("INSERT INTO admin_tasks (id,application_id,assigned_admin_id,created_by,title,description,priority,status,due_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(randomId("tsk_"), applicationId, membership.id, membership.id, title, safeText(body.description, 2000), ["low","normal","high","urgent"].includes(safeText(body.priority,20)) ? safeText(body.priority,20) : "normal", "open", Number.isFinite(Number(body.dueAt)) ? Number(body.dueAt) : null, now, now).run(); await audit("admin_task_created", "task", null, session.user.id, { title }); return json({ ok: true }); }
    const id = safeText(body.id, 100); const status = ["open","in_progress","completed","cancelled"].includes(safeText(body.status,30)) ? safeText(body.status,30) : "open"; await portalEnv.DB.prepare("UPDATE admin_tasks SET status=?,completed_at=?,updated_at=? WHERE id=?").bind(status, status === "completed" ? now : null, now, id).run(); await audit("admin_task_updated", "task", id, session.user.id, { status }); return json({ ok: true });
  }
  if (action === "privacy_complete") {
    const roleSession = await requireAdminRole(request, ["superadmin","support"]); if (roleSession.error || !roleSession.user) return roleSession.error!; const id = safeText(body.id, 100); await portalEnv.DB.prepare("UPDATE user_data_requests SET status='completed',admin_note=?,completed_at=? WHERE id=?").bind(safeText(body.adminNote, 2000), now, id).run(); await audit("privacy_request_completed", "data_request", id, session.user.id); return json({ ok: true });
  }
  if (action === "casevault_queue") {
    const applicationId = safeText(body.applicationId, 100); if (!applicationId) return json({ error: "Application ID is required." }, 400); const id = randomId("hnd_"); await portalEnv.DB.prepare("INSERT INTO integration_handoffs (id,application_id,provider,external_reference,status,payload_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(id, applicationId, "casevault", safeText(body.externalReference, 200) || null, "queued", "{}", now, now).run(); await audit("casevault_handoff_queued", "application", applicationId, session.user.id, { handoffId: id }); return json({ ok: true, id });
  }
  if (action === "refund_request" || action === "refund_execute") {
    const roleSession = await requireAdminRole(request, ["finance"]); if (roleSession.error || !roleSession.user || !roleSession.membership) return roleSession.error!;
    if (action === "refund_request") { const paymentId = safeText(body.paymentId, 100); const payment = await portalEnv.DB.prepare("SELECT amount_minor AS amountMinor,refunded_minor AS refundedMinor,status FROM payments WHERE id=?").bind(paymentId).first<{ amountMinor: number; refundedMinor: number; status: string }>(); const amount = Math.trunc(Number(body.amountMinor)); if (!payment || payment.status !== "paid" || !Number.isFinite(amount) || amount < 1 || amount > payment.amountMinor - payment.refundedMinor) return json({ error: "Refund amount exceeds the refundable payment balance." }, 400); const id = randomId("rfd_"); await portalEnv.DB.prepare("INSERT INTO payment_refunds (id,payment_id,amount_minor,reason,status,requested_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(id, paymentId, amount, safeText(body.reason, 500) || "Customer request", "requested", roleSession.membership.id, now, now).run(); await audit("refund_requested", "payment", paymentId, session.user.id, { refundId: id, amount }); return json({ ok: true, id }); }
    const id = safeText(body.id, 100); const refund = await portalEnv.DB.prepare(`SELECT r.id,r.amount_minor AS amountMinor,r.status,p.id AS paymentId,p.provider,p.currency,p.provider_reference AS providerReference,p.provider_capture_reference AS captureReference FROM payment_refunds r JOIN payments p ON p.id=r.payment_id WHERE r.id=? LIMIT 1`).bind(id).first<{ id: string; amountMinor: number; status: string; paymentId: string; provider: string; currency: string; providerReference: string; captureReference: string | null }>(); if (!refund || refund.status !== "requested") return json({ error: "Refund request is not available." }, 409);
    let providerReference = "";
    try {
      if (refund.provider === "paypal") { if (!refund.captureReference) throw new Error("This PayPal payment has no captured-payment reference."); const token = await paypalAccessToken(); const response = await fetch(`${paypalBaseUrl()}/v2/payments/captures/${encodeURIComponent(refund.captureReference)}/refund`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "content-type": "application/json", "PayPal-Request-Id": id }, body: JSON.stringify({ amount: { currency_code: refund.currency, value: (refund.amountMinor / 100).toFixed(2) } }) }); const data = await response.json() as { id?: string; message?: string }; if (!response.ok || !data.id) throw new Error(data.message || "PayPal rejected the refund."); providerReference = data.id; }
      else if (refund.provider === "paystack") { if (!portalEnv.PAYSTACK_SECRET_KEY) throw new Error("Paystack is not configured."); const response = await fetch("https://api.paystack.co/refund", { method: "POST", headers: { Authorization: `Bearer ${portalEnv.PAYSTACK_SECRET_KEY}`, "content-type": "application/json" }, body: JSON.stringify({ transaction: refund.providerReference, amount: refund.amountMinor }) }); const data = await response.json() as { status?: boolean; message?: string; data?: { id?: number; transaction?: { reference?: string } } }; if (!response.ok || !data.status) throw new Error(data.message || "Paystack rejected the refund."); providerReference = String(data.data?.id || data.data?.transaction?.reference || "paystack-refund"); }
      else throw new Error("This payment provider does not support automated refunds.");
    } catch (error) { const message = error instanceof Error ? error.message.slice(0, 300) : "Refund failed."; await portalEnv.DB.prepare("UPDATE payment_refunds SET status='failed',updated_at=? WHERE id=?").bind(now, id).run(); await audit("refund_failed", "payment", refund.paymentId, session.user.id, { refundId: id, message }); return json({ error: message }, 502); }
    await portalEnv.DB.batch([portalEnv.DB.prepare("UPDATE payment_refunds SET status='completed',provider_reference=?,approved_by=?,updated_at=?,completed_at=? WHERE id=?").bind(providerReference, roleSession.membership.id, now, now, id), portalEnv.DB.prepare("UPDATE payments SET refunded_minor=refunded_minor+?,status=CASE WHEN refunded_minor+?>=amount_minor THEN 'refunded' ELSE status END,updated_at=? WHERE id=?").bind(refund.amountMinor, refund.amountMinor, now, refund.paymentId)]); await audit("refund_completed", "payment", refund.paymentId, session.user.id, { refundId: id, amount: refund.amountMinor, providerReference }); return json({ ok: true, providerReference });
  }
  return json({ error: "Unsupported platform action." }, 400);
}
