CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY NOT NULL, email TEXT NOT NULL, country_residence TEXT NOT NULL, preferred_plan TEXT NOT NULL DEFAULT 'standard', email_verified_at INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE TABLE IF NOT EXISTS login_codes (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, code_hash TEXT NOT NULL, expires_at INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, consumed_at INTEGER, ip_hash TEXT, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_login_codes_user_created ON login_codes(user_id, created_at);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, token_hash TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, revoked_at INTEGER);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, plan TEXT NOT NULL, provider TEXT NOT NULL, amount_minor INTEGER NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, provider_reference TEXT, checkout_url TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, paid_at INTEGER);
CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_provider_reference ON payments(provider, provider_reference);
CREATE INDEX IF NOT EXISTS idx_payments_user_created ON payments(user_id, created_at);
CREATE TABLE IF NOT EXISTS entitlements (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, payment_id TEXT NOT NULL, plan TEXT NOT NULL, status TEXT NOT NULL, activated_at INTEGER NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_entitlements_payment ON entitlements(payment_id);
CREATE INDEX IF NOT EXISTS idx_entitlements_user_status ON entitlements(user_id, status);
CREATE TABLE IF NOT EXISTS applications (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, status TEXT NOT NULL, current_section INTEGER NOT NULL DEFAULT 1, answers_json TEXT NOT NULL DEFAULT '{}', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, submitted_at INTEGER);
CREATE UNIQUE INDEX IF NOT EXISTS idx_applications_user ON applications(user_id);
CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status);
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, application_id TEXT NOT NULL, r2_key TEXT NOT NULL, file_name TEXT NOT NULL, content_type TEXT NOT NULL, size INTEGER NOT NULL, status TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_documents_r2_key ON documents(r2_key);
CREATE INDEX IF NOT EXISTS idx_documents_user_created ON documents(user_id, created_at);
CREATE TABLE IF NOT EXISTS audit_events (id TEXT PRIMARY KEY NOT NULL, event TEXT NOT NULL, actor_user_id TEXT, entity_type TEXT NOT NULL, entity_id TEXT, metadata_json TEXT NOT NULL DEFAULT '{}', created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_audit_events_entity_created ON audit_events(entity_type, entity_id, created_at);
PRAGMA optimize;
