"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type AdminView = "overview" | "applications" | "payments" | "appointments" | "activity";
type ApplicationRow = { id: string; publicId: string; reviewStatus: string; submittedAt: number | null; updatedAt: number; reviewDueAt: number | null; reportPublishedAt: number | null; casevaultStatus: string; email: string; fullName: string | null; preferredDestination: string | null; assignedTo: string | null };
type PaymentRow = { id: string; plan: string; provider: string; amountMinor: number; currency: string; status: string; providerReference: string | null; createdAt: number; paidAt: number | null; email: string };
type ActivityRow = { id: string; event: string; entityType: string; entityId: string | null; createdAt: number; actorEmail: string | null };
type AppointmentRow = { id: string; publicId: string; applicationPublicId: string; email: string; status: string; requestedStart: number; durationMinutes: number; timezone: string; applicantNote: string; confirmedStart: number | null; meetingUrl: string | null; adminNote: string; provider: string; providerBookingUrl: string | null; cancelUrl: string | null; rescheduleUrl: string | null; completedAt: number | null; createdAt: number; updatedAt: number };
type Overview = { metrics: { total: number; awaiting: number; inReview: number; needsInformation: number; completed: number; overdue: number }; applications: ApplicationRow[]; payments: PaymentRow[]; appointments: AppointmentRow[]; activity: ActivityRow[]; admins: Array<{ id: string; role: string; email: string }> };
type Detail = { application: ApplicationRow & { answers: Record<string, string>; countryResidence: string; plan: string | null; currentSection: number; casevaultReference: string | null; retentionUntil: number | null }; notes: Array<{ id: string; note: string; createdAt: number; authorEmail: string }>; documents: Array<{ id: string; fileName: string; contentType: string; size: number; createdAt: number }>; payments: PaymentRow[]; messages: Array<{ id: string; senderRole: string; kind: string; subject: string; body: string; status: string; dueAt: number | null; createdAt: number }>; reports: Array<{ id: string; version: number; fileName: string; size: number; status: string; summary: string; publishedAt: number | null }>; emails: Array<{ id: string; category: string; subject: string; status: string; attempts: number; lastError: string | null; createdAt: number; sentAt: number | null }> };

const statusLabels: Record<string, string> = { draft: "Draft", submitted: "Awaiting review", in_review: "In review", needs_information: "Needs information", completed: "Completed", closed: "Closed" };
const adminNav: Array<{ id: AdminView; label: string; symbol: string }> = [{ id: "overview", label: "Overview", symbol: "O" }, { id: "applications", label: "Applications", symbol: "A" }, { id: "payments", label: "Payments", symbol: "P" }, { id: "appointments", label: "Appointments", symbol: "C" }, { id: "activity", label: "Audit activity", symbol: "L" }];
const money = (amount: number, currency: string) => new Intl.NumberFormat(currency === "NGN" ? "en-NG" : "en-US", { style: "currency", currency, maximumFractionDigits: currency === "NGN" ? 0 : 2 }).format(amount / 100);
const date = (value: number | null) => value ? new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "—";
const dateTimeInput = (value: number) => { const local = new Date(value - new Date(value).getTimezoneOffset() * 60000); return local.toISOString().slice(0, 16); };

export function AdminClient() {
  const [access, setAccess] = useState<"checking" | "signed_out" | "forbidden" | "ready">("checking"); const [email, setEmail] = useState(""); const [view, setView] = useState<AdminView>("overview"); const [overview, setOverview] = useState<Overview | null>(null); const [selected, setSelected] = useState<string | null>(null); const [detail, setDetail] = useState<Detail | null>(null); const [search, setSearch] = useState(""); const [filter, setFilter] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const sessionResponse = await fetch("/api/portal/session", { cache: "no-store" }); const session = await sessionResponse.json() as { authenticated?: boolean; user?: { email?: string; admin?: boolean } | null }; if (!session.authenticated) return setAccess("signed_out"); if (!session.user?.admin) return setAccess("forbidden"); setEmail(session.user.email || ""); const params = new URLSearchParams(); if (search) params.set("search", search); if (filter) params.set("status", filter); const response = await fetch(`/api/admin/overview?${params}`, { cache: "no-store" }); if (!response.ok) return setAccess(response.status === 403 ? "forbidden" : "signed_out"); setOverview(await response.json() as Overview); setAccess("ready"); } catch { setAccess("signed_out"); } }, [filter, search]);
  // The initial secure operations read resolves into client state.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const openApplication = async (publicId: string) => { setSelected(publicId); setDetail(null); const response = await fetch(`/api/admin/application?id=${encodeURIComponent(publicId)}`, { cache: "no-store" }); if (response.ok) setDetail(await response.json() as Detail); };
  const updateReview = async (reviewStatus: string, assignedAdminId = "") => { if (!selected) return; setBusy(true); const response = await fetch("/api/admin/application", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ publicId: selected, reviewStatus, assignedAdminId }) }); const result = await response.json() as { notification?: string; error?: string }; setBusy(false); if (!response.ok) return setMessage(result.error || "Unable to update this application."); setMessage(result.notification === "sent" ? "Review completed and the applicant was emailed." : result.notification === "queued" ? "Review completed. Email delivery is queued for retry." : "Review status updated."); await Promise.all([load(), openApplication(selected)]); };
  const addNote = async (note: string) => { if (!selected || !note.trim()) return; setBusy(true); const response = await fetch("/api/admin/application", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ publicId: selected, note }) }); setBusy(false); if (!response.ok) return setMessage("Unable to save the note."); setMessage("Internal note saved."); await openApplication(selected); };
  const filteredApplications = useMemo(() => overview?.applications || [], [overview]);
  if (access !== "ready") return <AdminAccess state={access} onAuthenticated={load} onSwitchAccount={async () => { await fetch("/api/portal/session", { method: "DELETE" }); setAccess("signed_out"); }} />;
  // Case workspace uses a full navigation so its protected client state initializes cleanly.
  // eslint-disable-next-line @next/next/no-html-link-for-pages
  return <div className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="admin-logo"><Image src="/migrz-logo.png" alt="Migrz" width={443} height={84} priority /></Link><div><span>Operations workspace</span><strong>Migrz Admin</strong></div><nav>{adminNav.map((item) => <button key={item.id} className={view === item.id ? "is-active" : ""} onClick={() => { setView(item.id); setSelected(null); }}><span>{item.symbol}</span>{item.label}</button>)}<a href="/admin/operations"><span>W</span>Case workspace</a><a href="/admin/platform"><span>X</span>Platform control</a></nav><small>Restricted to authorised Migrz staff.</small></aside><div className="admin-app"><header className="admin-topbar"><div><span>Live operations</span><strong>{email}</strong></div><div><button onClick={() => void load()}>Refresh</button><a href="/admin/operations">Case workspace</a><a href="/admin/platform">Platform control</a><Link href="/">Applicant portal</Link></div></header><main className="admin-main">
    {view === "overview" && overview && <><section className="admin-heading"><div><span className="portal-eyebrow">Command centre</span><h1>Assessment operations.</h1><p>Monitor paid access, submitted records, review work and service delivery from one private workspace.</p></div><button onClick={() => setView("applications")}>Open review queue →</button></section><section className="admin-metrics">{[["Total applications",overview.metrics.total],["Awaiting review",overview.metrics.awaiting],["In review",overview.metrics.inReview],["Needs information",overview.metrics.needsInformation],["Completed",overview.metrics.completed]].map(([label,value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="admin-grid"><AdminApplicationTable rows={overview.applications.slice(0,8)} onOpen={openApplication} /><section className="admin-panel"><div className="admin-panel-title"><span>Recent payments</span><button onClick={() => setView("payments")}>View all</button></div><div className="admin-payment-list">{overview.payments.slice(0,6).map((payment) => <article key={payment.id}><div><strong>{payment.email}</strong><small>{payment.provider} · {payment.plan}</small></div><span>{money(payment.amountMinor,payment.currency)}</span><i className={`admin-status is-${payment.status}`}>{payment.status}</i></article>)}</div></section></section></>}
    {view === "applications" && overview && <><section className="admin-heading is-compact"><div><span className="portal-eyebrow">Review queue</span><h1>Applications</h1></div></section><section className="admin-filters"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, email or submission ID" /><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">All statuses</option>{Object.entries(statusLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><button onClick={() => void load()}>Apply filters</button></section><AdminApplicationTable rows={filteredApplications} onOpen={openApplication} /></>}
    {view === "payments" && overview && <><section className="admin-heading is-compact"><div><span className="portal-eyebrow">Finance record</span><h1>Payments</h1></div></section><section className="admin-panel admin-table-panel"><table><thead><tr><th>Applicant</th><th>Plan</th><th>Provider</th><th>Amount</th><th>Status</th><th>Paid</th></tr></thead><tbody>{overview.payments.map((payment) => <tr key={payment.id}><td><strong>{payment.email}</strong><small>{payment.providerReference || payment.id}</small></td><td>{payment.plan}</td><td>{payment.provider}</td><td>{money(payment.amountMinor,payment.currency)}</td><td><i className={`admin-status is-${payment.status}`}>{payment.status}</i></td><td>{date(payment.paidAt)}</td></tr>)}</tbody></table></section></>}
    {view === "appointments" && overview && <><section className="admin-heading is-compact"><div><span className="portal-eyebrow">Assessment conversations</span><h1>Appointments</h1><p>Confirm requested call times, add secure meeting details, and keep every conversation tied to its submission.</p></div></section><section className="admin-appointment-list">{overview.appointments.map((appointment) => <AdminAppointment key={appointment.id} appointment={appointment} onSaved={load} />)}{!overview.appointments.length && <div className="admin-panel admin-empty">No appointment requests yet.</div>}</section></>}
    {view === "activity" && overview && <><section className="admin-heading is-compact"><div><span className="portal-eyebrow">Accountability</span><h1>Audit activity</h1></div></section><section className="admin-panel admin-activity">{overview.activity.map((item) => <article key={item.id}><span>{item.event.replaceAll("_"," ")}</span><strong>{item.actorEmail || "System"}</strong><small>{item.entityType} · {date(item.createdAt)}</small></article>)}</section></>}
  </main></div>{selected && <ApplicationDrawer detail={detail} admins={overview?.admins || []} busy={busy} message={message} onClose={() => { setSelected(null); setDetail(null); setMessage(""); }} onUpdate={updateReview} onNote={addNote} />}</div>;
}

function AdminAccess({ state, onAuthenticated, onSwitchAccount }: { state: "checking" | "signed_out" | "forbidden"; onAuthenticated: () => Promise<void>; onSwitchAccount: () => Promise<void> }) {
  const [stage, setStage] = useState<"email" | "code">("email");
  const [email, setEmail] = useState("control@migrzz.com");
  const [code, setCode] = useState("");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const requestCode = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch("/api/portal/auth/request-code", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, countryResidence: "NG", plan: "standard" }) }); const data = await response.json() as { error?: string }; if (!response.ok) setMessage(data.error || "Unable to send the sign-in code."); else setStage("code"); } catch { setMessage("Unable to reach secure sign-in. Please try again."); } finally { setBusy(false); } };
  const verifyCode = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch("/api/portal/auth/verify-code", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, code }) }); const data = await response.json() as { error?: string }; if (!response.ok) setMessage(data.error || "That code is invalid or expired."); else await onAuthenticated(); } catch { setMessage("Unable to verify the code. Please try again."); } finally { setBusy(false); } };
  return <main className="admin-access"><Image src="/migrz-logo.png" alt="Migrz" width={443} height={84} priority /><span className="portal-eyebrow">Restricted operations</span><h1>{state === "checking" ? "Checking secure access…" : state === "signed_out" ? "Sign in to Migrz operations." : "This account is not an authorised administrator."}</h1><p>Admin access uses a one-time email code and a separate server-side role check. No admin password is stored.</p>{state === "signed_out" && <form className="admin-signin-form" onSubmit={stage === "email" ? requestCode : verifyCode}>{stage === "email" ? <label>Administrator email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" required /></label> : <><label>Six-digit code sent to {email}<input value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required /></label><button type="button" className="admin-secondary-button" onClick={() => { setStage("email"); setCode(""); setMessage(""); }}>Use another email</button></>}<button type="submit" disabled={busy}>{busy ? "Please wait…" : stage === "email" ? "Email secure code →" : "Verify and open operations →"}</button>{message && <small role="alert">{message}</small>}</form>}{state === "forbidden" && <button className="admin-switch-button" onClick={() => void onSwitchAccount()}>Sign in as another administrator →</button>}</main>;
}
function AdminAppointment({ appointment, onSaved }: { appointment: AppointmentRow; onSaved: () => Promise<void> }) {
  const [status, setStatus] = useState(appointment.status); const [confirmedStart, setConfirmedStart] = useState(dateTimeInput(appointment.confirmedStart || appointment.requestedStart)); const [meetingUrl, setMeetingUrl] = useState(appointment.meetingUrl || ""); const [adminNote, setAdminNote] = useState(appointment.adminNote || ""); const [message, setMessage] = useState(appointment.provider !== "calendly" && !appointment.meetingUrl ? "Save this appointment to create the Calendly meeting and applicant join link." : ""); const [busy, setBusy] = useState(false);
  const save = async () => { setBusy(true); setMessage(""); const response = await fetch("/api/admin/appointments", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: appointment.id, status, confirmedStart: confirmedStart ? new Date(confirmedStart).getTime() : null, meetingUrl, adminNote }) }); const result = await response.json() as { error?: string; warning?: string; notification?: string }; setBusy(false); if (!response.ok) return setMessage(result.error || "Unable to update the appointment."); setMessage(result.warning || (status === "completed" ? "Call completed. The applicant was notified and next steps are now visible." : status === "confirmed" ? "Appointment confirmed and applicant notified." : "Appointment updated.")); await onSaved(); };
  return <article className="admin-appointment"><header><div><span>{appointment.publicId}</span><strong>{appointment.email}</strong><small>Assessment {appointment.applicationPublicId} · {appointment.provider === "calendly" ? "Calendly booking" : appointment.providerBookingUrl ? "Applicant Calendly booking" : "Manual booking"}</small></div><i className={`admin-status is-${appointment.status}`}>{appointment.status.replaceAll("_", " ")}</i></header><div className="admin-appointment-request"><span>Applicant requested</span><strong>{new Date(appointment.requestedStart).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}</strong><small>{appointment.durationMinutes} minutes · {appointment.timezone}</small>{appointment.applicantNote && <p>{appointment.applicantNote}</p>}{appointment.providerBookingUrl && <a className="portal-secondary-link" href={appointment.providerBookingUrl} target="_blank" rel="noreferrer">Preview applicant booking page</a>}</div><div className="admin-appointment-controls"><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="requested">Requested</option><option value="confirmed">Confirmed</option><option value="rescheduled">Rescheduled</option><option value="completed">Call completed</option><option value="no_show">Applicant did not attend</option><option value="cancelled">Cancelled</option></select></label><label>Confirmed date and time<input type="datetime-local" value={confirmedStart} onChange={(event) => setConfirmedStart(event.target.value)} /></label><label>Meeting link<input type="url" value={meetingUrl} onChange={(event) => setMeetingUrl(event.target.value)} placeholder="https://meet.google.com/…" /></label><label className="admin-appointment-note">Applicant-facing outcome / next steps<textarea value={adminNote} onChange={(event) => setAdminNote(event.target.value)} placeholder="After the call, add the agreed next action before marking it complete." maxLength={1000} /></label><button disabled={busy || (status === "completed" && !adminNote.trim()) || Boolean(appointment.providerBookingUrl && status !== "completed")} onClick={() => void save()}>{busy ? "Saving…" : status === "completed" ? "Complete call & notify applicant" : appointment.providerBookingUrl ? "Waiting for applicant booking" : "Save appointment"}</button>{message && <small role="status">{message}</small>}</div></article>;
}
function AdminApplicationTable({ rows, onOpen }: { rows: ApplicationRow[]; onOpen: (id: string) => void }) { return <section className="admin-panel admin-table-panel"><div className="admin-panel-title"><span>Application queue</span><small>{rows.length} records</small></div><table><thead><tr><th>Submission</th><th>Applicant</th><th>Destination</th><th>Status</th><th>Submitted</th><th></th></tr></thead><tbody>{rows.map((application) => <tr key={application.id}><td><strong>{application.publicId}</strong></td><td><strong>{application.fullName || "Name pending"}</strong><small>{application.email}</small></td><td>{application.preferredDestination || "Not selected"}</td><td><i className={`admin-status is-${application.reviewStatus}`}>{statusLabels[application.reviewStatus] || application.reviewStatus}</i></td><td>{date(application.submittedAt)}</td><td><button onClick={() => onOpen(application.publicId)}>Open →</button></td></tr>)}</tbody></table>{!rows.length && <p className="admin-empty">No applications match this view.</p>}</section>; }
function ApplicationDrawer({ detail, admins, busy, message, onClose, onUpdate, onNote }: { detail: Detail | null; admins: Overview["admins"]; busy: boolean; message: string; onClose: () => void; onUpdate: (status: string, adminId?: string) => Promise<void>; onNote: (note: string) => Promise<void> }) { const [status, setStatus] = useState(""); const [assignee, setAssignee] = useState(""); const [note, setNote] = useState("");
  // The selected secure record initializes editable operations controls.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (detail) { setStatus(detail.application.reviewStatus); setAssignee(admins.find((admin) => admin.email === detail.application.assignedTo)?.id || ""); } }, [admins, detail]); return <><button className="admin-drawer-scrim" onClick={onClose} aria-label="Close application" /><aside className="admin-drawer"><header><div><span>{detail?.application.publicId || "Loading…"}</span><h2>{detail?.application.answers.fullName || "Application record"}</h2><p>{detail?.application.email}</p></div><button onClick={onClose}>×</button></header>{!detail ? <p>Loading secure record…</p> : <div className="admin-drawer-body"><section className="admin-review-controls"><label>Review status<select value={status} onChange={(event) => setStatus(event.target.value)}>{Object.entries(statusLabels).filter(([value]) => value !== "draft").map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Assigned to<select value={assignee} onChange={(event) => setAssignee(event.target.value)}><option value="">Unassigned</option>{admins.map((admin) => <option key={admin.id} value={admin.id}>{admin.email}</option>)}</select></label><button disabled={busy} onClick={() => void onUpdate(status,assignee)}>Save review state</button>{message && <small>{message}</small>}</section><section><span className="portal-eyebrow">Applicant record</span><dl>{Object.entries(detail.application.answers).map(([key,value]) => <div key={key}><dt>{key.replace(/([A-Z])/g," $1")}</dt><dd>{value || "—"}</dd></div>)}</dl></section><section><span className="portal-eyebrow">Documents</span>{detail.documents.length ? detail.documents.map((document) => <a className="admin-document" key={document.id} href={`/api/admin/documents/download?id=${encodeURIComponent(document.id)}`}><span>{document.fileName}</span><small>{Math.ceil(document.size/1024)} KB · Download</small></a>) : <p>No documents uploaded.</p>}</section><section><span className="portal-eyebrow">Internal notes</span><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add a private operational note…" /><button disabled={busy || !note.trim()} onClick={() => { void onNote(note).then(() => setNote("")); }}>Save internal note</button>{detail.notes.map((item) => <article className="admin-note" key={item.id}><p>{item.note}</p><small>{item.authorEmail} · {date(item.createdAt)}</small></article>)}</section></div>}</aside></>; }
