import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const routes=["/","/what-makes-us-different/","/eu/de/germany-eu-blue-card","/au/australia-global-talent","/uae/dubai-golden-visa","/ca/express-entry","/ca/provincial-nominee-program","/ca/canada-immigration","/uk/innovator-founder-visa","/uk/global-talent-visa","/us/niw","/us/eb-1a","/process/","/98-success-rate/","/customers/","/faqs/","/about/"];

async function worker(){const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}-${Math.random()}`);return(await import(workerUrl.href)).default;}
async function fetchRoute(path){const w=await worker();const env={ASSETS:{fetch:async()=>new Response("Not found",{status:404})}};const ctx={waitUntil(){},passThroughOnException(){}};const request=new Request(`https://migrzz.com${path}`,{headers:{accept:"text/html",host:"migrzz.com","x-forwarded-host":"migrzz.com","x-forwarded-proto":"https"}});let response=await w.fetch(request,env,ctx);if([307,308].includes(response.status)){const location=response.headers.get("location");response=await w.fetch(new Request(new URL(location,request.url),request),env,ctx);}return response;}

test("renders every canonical Migrz page",async()=>{for(const route of routes){const response=await fetchRoute(route);assert.equal(response.status,200,route);const html=await response.text();assert.match(html,/<title>.+Migrz/i,route);assert.match(html,/Start assessment|Start professional assessment|Start your/i,route);assert.match(html,/migrz-logo\.png/i,route);assert.doesNotMatch(html,/codex-preview|react-loading-skeleton|UI DESIGN LAB/i,route);}});

test("homepage renders the human-led monochrome direction",async()=>{const response=await fetchRoute("/");const html=await response.text();assert.match(html,/Your work has crossed borders/);assert.match(html,/Reviewed by a person/);assert.match(html,/A professional assessment, not an online score/);assert.match(html,/Strategy before paperwork/);assert.doesNotMatch(html,/Illustrative profile match|Your strongest pathways|\/100/);});

test("pathway pages use current programs and official guidance",async()=>{const au=await(await fetchRoute("/au/australia-global-talent/")).text();assert.match(au,/National Innovation Visa/);assert.match(au,/replaced the former Global Talent/i);const ca=await(await fetchRoute("/ca/provincial-nominee-program/")).text();assert.match(ca,/600 additional CRS points/);const uae=await(await fetchRoute("/uae/dubai-golden-visa/")).text();assert.match(uae,/Official UAE Golden visa guidance/);});

test("crawler assets cover all canonical pages",async()=>{const sitemap=await fetchRoute("/sitemap.xml");assert.equal(sitemap.status,200);const xml=await sitemap.text();for(const route of routes)assert.match(xml,new RegExp(`https://migrzz\\.com${route.replaceAll("/","\\/")}`));const robots=await fetchRoute("/robots.txt");assert.equal(robots.status,200);assert.match(await robots.text(),/Sitemap: https:\/\/migrzz\.com\/sitemap\.xml/);const manifest=await fetchRoute("/manifest.webmanifest");assert.equal(manifest.status,200);assert.match(await manifest.text(),/"name"\s*:\s*"Migrz"/);});

test("every pathway includes detailed guidance",async()=>{for(const route of routes.filter(route=>route.split("/").filter(Boolean).length>1)){const html=await(await fetchRoute(route)).text();assert.match(html,/Understanding the route/);assert.match(html,/Eligibility logic/);assert.match(html,/Evidence examples/);assert.match(html,/Important limitations/);assert.ok(html.replace(/<[^>]+>/g," ").split(/\s+/).filter(Boolean).length>650,`${route} should contain substantive copy`);}});

test("mobile navigation and responsive monochrome layouts are present",async()=>{const [css,components]=await Promise.all([readFile(new URL("../app/globals.css",import.meta.url),"utf8"),readFile(new URL("../app/site-components.tsx",import.meta.url),"utf8")]);assert.match(css,/@media\(max-width:640px\)/);assert.match(css,/overflow-x:hidden/);assert.match(css,/--ink:#050505;--ink2:#111;--paper:#fff;--white:#fff;--accent:#fff/);assert.match(components,/className="mobile-menu"/);assert.match(components,/aria-label="Open menu"/);});
