import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const routes=["/","/what-makes-us-different","/eu/de/germany-eu-blue-card","/au/australia-global-talent","/uae/dubai-golden-visa","/ca/express-entry","/ca/provincial-nominee-program","/ca/canada-immigration","/uk/innovator-founder-visa","/uk/global-talent-visa","/us/niw","/us/eb-1a","/process","/98-success-rate","/case-studies","/customers","/faqs","/about","/team","/assessment","/privacy","/terms","/cookie-policy","/accessibility","/disclaimer"];

async function worker(){const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}-${Math.random()}`);return(await import(workerUrl.href)).default;}
async function fetchRoute(path,hostname="migrzz.com"){const w=await worker();const env={ASSETS:{fetch:async()=>new Response("Not found",{status:404})}};const ctx={waitUntil(){},passThroughOnException(){}};let request=new Request(`https://${hostname}${path}`,{headers:{accept:"text/html",host:hostname,"x-forwarded-host":hostname,"x-forwarded-proto":"https"}});let response=await w.fetch(request,env,ctx);if([301,302,303,307,308].includes(response.status)){const location=response.headers.get("location");request=new Request(new URL(location,request.url),request);response=await w.fetch(request,env,ctx);}return response;}

test("renders every canonical Migrz page",async()=>{for(const route of routes){const response=await fetchRoute(route);assert.equal(response.status,200,route);const html=await response.text();assert.match(html,/<title>.+Migrz/i,route);assert.match(html,/Start assessment|Start professional assessment|Start your/i,route);assert.match(html,/migrz-logo\.png/i,route);assert.doesNotMatch(html,/codex-preview|react-loading-skeleton|UI DESIGN LAB/i,route);}});

test("homepage renders the human-led monochrome direction",async()=>{const response=await fetchRoute("/");const html=await response.text();assert.match(html,/Your work has crossed borders/);assert.match(html,/Reviewed by a person/);assert.match(html,/A professional assessment, not an online score/);assert.match(html,/Strategy before paperwork/);assert.match(html,/Assessment first/);assert.doesNotMatch(html,/Illustrative profile match|Your strongest pathways|\/100/);});

test("about story uses an expansive editorial layout",async()=>{const html=await(await fetchRoute("/about")).text();assert.match(html,/story-editorial/);assert.match(html,/The route existed\. The evidence was being missed/);assert.match(html,/Depth before volume/);const css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");assert.match(css,/\.story-chapters\{display:grid;grid-template-columns:1fr 1fr/);assert.match(css,/@media\(max-width:1000px\)\{\.story-opening\{grid-template-columns:1fr/);assert.match(css,/@media\(max-width:640px\)\{\.story-editorial\{padding:78px 6%/);});

test("pathway pages use current programs and official guidance",async()=>{const au=await(await fetchRoute("/au/australia-global-talent/")).text();assert.match(au,/National Innovation Visa/);assert.match(au,/replaced the former Global Talent/i);const ca=await(await fetchRoute("/ca/provincial-nominee-program/")).text();assert.match(ca,/600 additional CRS points/);const uae=await(await fetchRoute("/uae/dubai-golden-visa/")).text();assert.match(uae,/Official UAE Golden visa guidance/);});

test("core selling pages contain substantive long-form guidance",async()=>{for(const route of ["/process/","/98-success-rate/","/what-makes-us-different/"]){const html=await(await fetchRoute(route)).text();const words=html.replace(/<[^>]+>/g," ").split(/\s+/).filter(Boolean);assert.ok(words.length>900,`${route} should contain more than 900 words, found ${words.length}`);}const results=await(await fetchRoute("/98-success-rate/")).text();assert.match(results,/Strong outcomes begin before the application is filed/);assert.match(results,/Four practical deliverables/);assert.match(results,/No invented certainty/);assert.doesNotMatch(results,/98%|next verification release|under reconciliation|current public record/i);const process=await(await fetchRoute("/process/")).text();assert.match(process,/Your role/);assert.match(process,/Migrz's role/);assert.match(process,/Timing and scope/);const difference=await(await fetchRoute("/what-makes-us-different/")).text();assert.match(difference,/10[\s\S]*A broader definition of success/);});

test("trust, proof, assessment, and policy pages are complete",async()=>{const team=await(await fetchRoute("/team")).text();assert.match(team,/Uchechukwu Ajuzieogu/);assert.match(team,/Maryangel Nnamdi/);assert.match(team,/Independent legal services/);const cases=await(await fetchRoute("/case-studies")).text();assert.match(cases,/Dr\. Chinwe A\./);assert.match(cases,/Ibrahim K\./);assert.match(cases,/Alex P\./);assert.match(cases,/individual experiences/);assert.doesNotMatch(cases,/future proof release/i);const assessment=await(await fetchRoute("/assessment")).text();assert.match(assessment,/\$350/);assert.match(assessment,/\$550/);assert.match(assessment,/Written eligibility report/);assert.match(assessment,/48-hour target/);const results=await(await fetchRoute("/98-success-rate")).text();assert.match(results,/A written recommendation you can act on/);assert.doesNotMatch(results,/3,738\+|98%/);for(const route of ["/privacy","/terms","/cookie-policy","/accessibility","/disclaimer"]){const html=await(await fetchRoute(route)).text();assert.match(html,/Effective 22 August 2026/);assert.ok(html.replace(/<[^>]+>/g," ").split(/\s+/).filter(Boolean).length>350,`${route} should be substantive`);}});

test("public copy contains no editorial prompts or dash punctuation",async()=>{const banned=/future proof release|next verification release|under reconciliation|current public record|removed from this build|should publish/i;for(const route of routes){const html=await(await fetchRoute(route)).text();assert.doesNotMatch(html,banned,route);const visible=html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ");assert.doesNotMatch(visible,/[—–]/,`${route} should not contain em or en dash punctuation`);}});

test("destination photography and branded arrows are rendered",async()=>{const home=await(await fetchRoute("/")).text();for(const image of ["us.webp","uk.webp","canada.webp","australia.webp","uae.webp"])assert.match(home,new RegExp(`/destinations/${image}`));const germany=await(await fetchRoute("/eu/de/germany-eu-blue-card/")).text();assert.match(germany,/\/destinations\/germany\.webp/);assert.match(home,/class="brand-arrow"/);assert.doesNotMatch(home,/>↗</);});

test("crawler assets cover all canonical pages",async()=>{const sitemap=await fetchRoute("/sitemap.xml");assert.equal(sitemap.status,200);const xml=await sitemap.text();for(const route of routes)assert.match(xml,new RegExp(`https://migrzz\\.com${route.replaceAll("/","\\/")}`));const robots=await fetchRoute("/robots.txt");assert.equal(robots.status,200);assert.match(await robots.text(),/Sitemap: https:\/\/migrzz\.com\/sitemap\.xml/);const manifest=await fetchRoute("/manifest.webmanifest");assert.equal(manifest.status,200);assert.match(await manifest.text(),/"name"\s*:\s*"Migrz"/);});

test("every page has complete unique SEO metadata and parseable schema",async()=>{const titles=new Set(),descriptions=new Set();for(const route of routes){const html=await(await fetchRoute(route)).text();const title=html.match(/<title>([^<]+)<\/title>/i)?.[1];const description=html.match(/<meta name="description" content="([^"]+)"/i)?.[1];const keywords=html.match(/<meta name="keywords" content="([^"]+)"/i)?.[1]?.split(",").map(value=>value.trim()).filter(Boolean);const canonical=html.match(/<link rel="canonical" href="([^"]+)"/i)?.[1];assert.ok(title,`${route} title`);assert.ok(description,`${route} description`);assert.equal(keywords?.length,20,`${route} should have exactly 20 mapped keywords`);assert.equal(new Set(keywords?.map(value=>value.toLowerCase())).size,20,`${route} keywords should be unique`);assert.equal(canonical,route==="/"?"https://migrzz.com":`https://migrzz.com${route}`,`${route} canonical should match the final URL`);assert.ok(!titles.has(title),`${route} title should be unique`);assert.ok(!descriptions.has(description),`${route} description should be unique`);titles.add(title);descriptions.add(description);const schemas=[...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].map(match=>JSON.parse(match[1]));assert.ok(schemas.length>=2,`${route} should inherit site schema and render page schema`);assert.ok(schemas.some(schema=>Array.isArray(schema["@graph"])&&schema["@graph"].some(node=>String(node["@id"]||"").includes("#webpage"))),`${route} should identify its WebPage entity`);}});

test("answer-engine discovery files expose search crawlers and canonical sources",async()=>{const robots=await(await fetchRoute("/robots.txt")).text();for(const agent of ["OAI-SearchBot","ChatGPT-User","Claude-SearchBot","Claude-User","Googlebot","Bingbot"])assert.match(robots,new RegExp(`User-agent: ${agent}`,"i"));const llms=await readFile(new URL("../public/llms.txt",import.meta.url),"utf8");assert.match(llms,/Canonical site: https:\/\/migrzz\.com\//);assert.match(llms,/Results and evidence method/);assert.doesNotMatch(llms,/98%|under reconciliation|removed from the current build/i);for(const route of routes.filter(Boolean))assert.match(llms+await(await fetchRoute("/sitemap.xml")).text(),new RegExp(`https://migrzz\\.com${route.replaceAll("/","\\/")}`));});

test("every pathway includes detailed guidance",async()=>{for(const route of routes.filter(route=>route.split("/").filter(Boolean).length>1)){const html=await(await fetchRoute(route)).text();assert.match(html,/Understanding the route/);assert.match(html,/Eligibility logic/);assert.match(html,/Evidence examples/);assert.match(html,/Important limitations/);assert.ok(html.replace(/<[^>]+>/g," ").split(/\s+/).filter(Boolean).length>650,`${route} should contain substantive copy`);}});

test("mobile navigation and responsive monochrome layouts are present",async()=>{const [css,components]=await Promise.all([readFile(new URL("../app/globals.css",import.meta.url),"utf8"),readFile(new URL("../app/site-components.tsx",import.meta.url),"utf8")]);assert.match(css,/@media\(max-width:640px\)/);assert.match(css,/overflow-x:hidden/);assert.match(css,/--ink:#050505;--ink2:#111;--paper:#fff;--white:#fff;--accent:#fff/);assert.match(components,/className="mobile-menu"/);assert.match(components,/aria-label="Menu"/);assert.match(components,/className="mobile-nav-links"/);assert.match(components,/\["09","FAQs","\/faqs"\]/);assert.match(css,/body:has\(\.mobile-menu\[open\]\)\{overflow:hidden\}/);assert.match(css,/\.mobile-nav-links a\{min-height:68px/);assert.match(css,/\.process-body\{margin:32px 0 0\}/);assert.match(css,/@media\(max-width:360px\)/);});

test("desktop footer is restored while mobile keeps branded accordion navigation",async()=>{const [html,css]=await Promise.all([(await fetchRoute("/")).text(),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]);assert.match(html,/class="footer-grid footer-grid-desktop"><div><span>Pathways<\/span>/);assert.match(css,/\.footer-grid-mobile\{display:none\}/);assert.match(css,/\.footer-grid-desktop\{display:none\}/);assert.equal((html.match(/class="footer-col"/g)||[]).length,4);assert.match(html,/class="footer-grid footer-grid-mobile"/);assert.match(html,/<summary>Pathways<\/summary>/);assert.match(html,/<summary>Company<\/summary>/);assert.match(html,/<summary>Resources<\/summary>/);assert.match(html,/<summary>Office<\/summary>/);assert.match(css,/\.footer-col:not\(\[open\]\)>\.footer-links\{display:none\}/);assert.match(css,/\.footer-col summary:after\{content:"\+"/);});

test("consent-aware analytics and assessment attribution are inherited by every page",async()=>{for(const route of routes){const html=await(await fetchRoute(route)).text();const headEnd=html.indexOf("</head>");assert.ok(headEnd>0,`${route} should render a document head`);const head=html.slice(0,headEnd);assert.match(head,/googletagmanager\.com\/gtag\/js\?id=G-8X3PLHV88L/,route);assert.match(head,/gtag\('config', 'G-8X3PLHV88L'/,route);assert.match(head,/apply\.migrzz\.com/,route);assert.doesNotMatch(head,/forms\.migrzz\.com/,route);assert.match(head,/migrz_analytics_consent/,route);assert.match(head,/clarity\.ms\/tag\//,route);assert.match(head,/uw607xjcnq/,route);assert.match(head,/connect\.facebook\.net\/en_US\/fbevents\.js/,route);assert.match(head,/fbq\('init', '1977570466130181'\)/,route);assert.match(html,/Cookie preferences/,route);assert.doesNotMatch(html,/facebook\.com\/tr\?id=1977570466130181(?:&|&amp;)ev=PageView(?:&|&amp;)noscript=1/,route);}});

test("assessment attribution and policy controls are implemented once for future pages",async()=>{const [analytics,footer]=await Promise.all([readFile(new URL("../app/analytics-consent.tsx",import.meta.url),"utf8"),readFile(new URL("../app/site-components.tsx",import.meta.url),"utf8")]);assert.match(analytics,/assessment_click/);assert.match(analytics,/migrz_source_page/);assert.match(analytics,/utm_campaign/);assert.match(analytics,/trackCustom/);assert.match(analytics,/data-cookie-settings/);for(const route of ["privacy","terms","cookie-policy","accessibility","disclaimer"])assert.match(footer,new RegExp(`href="/${route}"`));});

test("production routing keeps one canonical domain and preserves the legacy location URL",async()=>{const [worker,vite]=await Promise.all([readFile(new URL("../worker/index.ts",import.meta.url),"utf8"),readFile(new URL("../vite.config.ts",import.meta.url),"utf8")]);assert.match(vite,/MIGRZ_ENABLE_CUSTOM_DOMAINS === "1"/);assert.match(vite,/pattern: "migrzz\.com\/\*", zone_name: "migrzz\.com"/);assert.match(vite,/pattern: "www\.migrzz\.com\/\*", zone_name: "migrzz\.com"/);assert.match(vite,/routes: productionRoutes/);assert.match(vite,/workers_dev: true/);assert.match(worker,/url\.hostname === "www\.migrzz\.com"/);assert.match(worker,/url\.hostname = "migrzz\.com"/);assert.match(worker,/url\.pathname === "\/locations\.kml"/);assert.match(worker,/url\.pathname = "\/about"/);});

test("heroes use the distinctive Migrz movement system",async()=>{const [home,about,css]=await Promise.all([(await fetchRoute("/")).text(),(await fetchRoute("/about")).text(),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]);assert.match(home,/class="mobile-signal"/);assert.match(about,/class="hero-route-mark"/);assert.match(about,/Merit in motion/);assert.doesNotMatch(about,/hero-monogram/);assert.match(css,/\.home-hero \.human-review\{min-height:560px;background:#050505/);assert.match(css,/\.home-hero \.human-review\{display:none\}/);assert.match(css,/min-height:calc\(100svh - 116px\)/);assert.match(css,/\.hero-route-mark>strong/);});

test("applicant portal is payment-first, privately indexed, and routed through the apply subdomain",async()=>{const [portal,sitemap,css,server,client,countries,vite]=await Promise.all([(await fetchRoute("/","apply.migrzz.com")).text(),(await fetchRoute("/sitemap.xml")).text(),readFile(new URL("../app/globals.css",import.meta.url),"utf8"),readFile(new URL("../app/portal/server.ts",import.meta.url),"utf8"),readFile(new URL("../app/portal/portal-client.tsx",import.meta.url),"utf8"),readFile(new URL("../app/portal/countries.ts",import.meta.url),"utf8"),readFile(new URL("../vite.config.ts",import.meta.url),"utf8")]);assert.match(portal,/Applicant Portal \| Migrz/);assert.match(portal,/Checking secure access/);assert.match(portal,/name="robots" content="noindex, nofollow"/);assert.match(client,/Paystack/);assert.match(client,/PayPal/);assert.match(client,/\$350/);assert.match(client,/\$550/);assert.doesNotMatch(sitemap,/\/portal|apply\.migrzz\.com/);assert.match(server,/country === "NG" \? "paystack" : paypalSupportsResidence\(country\) \? "paypal" : "unsupported"/);assert.match(countries,/paypalCountryCodes/);assert.match(countries,/Nigeria/);assert.match(server,/ZEPTOMAIL_TOKEN/);assert.match(server,/x-paystack-signature|hmacHex/);assert.match(vite,/pattern: "apply\.migrzz\.com", custom_domain: true/);assert.match(css,/--navy:#10233f/);assert.match(css,/\.portal-mobile-nav/);assert.match(css,/body:has\(\.portal-gate\)>\.header/);});

test("submitted assessments lock into a review state and destinations are constrained",async()=>{const [client,route,options,css]=await Promise.all([readFile(new URL("../app/portal/portal-client.tsx",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/application/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/portal/options.ts",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]);assert.match(client,/applicationStatus === "submitted"/);assert.match(client,/Awaiting professional review/);assert.match(client,/Your assessment is with Migrz/);assert.match(client,/setApplicationStatus\("submitted"\)/);assert.match(client,/supportedDestinations\.map/);assert.match(route,/preferredDestination/);assert.match(route,/Select a destination currently supported by Migrz/);for(const country of ["United States","United Kingdom","Canada","Australia","Germany","United Arab Emirates"])assert.match(options,new RegExp(country));assert.match(css,/\.portal-submitted-card/);});

test("home dashboard derives status from the shared application record and never guesses while loading",async()=>{const [client,css]=await Promise.all([readFile(new URL("../app/portal/portal-client.tsx",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]);assert.match(client,/type ApplicationState/);assert.match(client,/refreshApplication/);assert.match(client,/window\.addEventListener\("focus", refreshOnFocus\)/);assert.match(client,/if \(!state\.loaded\) return <DashboardStatus/);assert.match(client,/if \(state\.error\) return <DashboardStatus/);assert.match(client,/Not started/);assert.match(client,/In progress/);assert.match(client,/Submitted for/);assert.match(client,/View submission status/);assert.match(client,/onApplicationChanged=\{refreshApplication\}/);assert.match(css,/\.portal-dashboard-state/);});

test("portal workflow, submission IDs, and admin operations reflect the real service sequence",async()=>{const [client,server,applicationRoute,adminPage,adminClient,overviewRoute,detailRoute,downloadRoute,migration,css]=await Promise.all([readFile(new URL("../app/portal/portal-client.tsx",import.meta.url),"utf8"),readFile(new URL("../app/portal/server.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/application/route.ts",import.meta.url),"utf8"),(await fetchRoute("/admin","apply.migrzz.com")).text(),readFile(new URL("../app/admin/admin-client.tsx",import.meta.url),"utf8"),readFile(new URL("../app/api/admin/overview/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/admin/application/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/admin/documents/download/route.ts",import.meta.url),"utf8"),readFile(new URL("../drizzle/0002_admin_operations.sql",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]);for(const step of ["Create account","Make payment","Add information","Submit assessment","Migrz review"])assert.match(client,new RegExp(step));assert.match(client,/Submission ID/);assert.match(server,/submissionPublicId/);assert.match(applicationRoute,/public_id AS publicId/);assert.match(adminPage,/name="robots" content="noindex, nofollow"/);for(const source of [overviewRoute,detailRoute,downloadRoute])assert.match(source,/requireAdmin\(request\)/);for(const feature of ["Applications","Payments","Audit activity","Internal notes","Assigned to"])assert.match(adminClient,new RegExp(feature));assert.match(detailRoute,/application_review_updated/);assert.match(detailRoute,/application_note_added/);assert.match(migration,/CREATE TABLE IF NOT EXISTS admins/);assert.match(migration,/CREATE TABLE IF NOT EXISTS application_notes/);assert.match(css,/\.admin-shell/);});

test("ZeptoMail accepts raw or prefixed tokens without exposing applicant data in logs",async()=>{const [server,email,route]=await Promise.all([readFile(new URL("../app/portal/server.ts",import.meta.url),"utf8"),readFile(new URL("../app/portal/email.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/auth/request-code/route.ts",import.meta.url),"utf8")]);assert.match(email,/config\.from \|\| "comms@migrzz\.com"/);assert.match(email,/replace\(\/\^zoho-enczapikey\\s\+\/i, ""\)/);assert.match(email,/Authorization: `Zoho-enczapikey \$\{token\}`/);assert.match(email,/ZeptoMail rejected a transactional email/);assert.match(server,/sendPortalEmail/);assert.doesNotMatch(route,/console\.error\([^\n]*\{[^\n]*email\s*[,}]/);});

test("Nigerian checkout uses a signed, expiring Wise quote with no hidden markup",async()=>{const [server,checkout,verify,client]=await Promise.all([readFile(new URL("../app/portal/server.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/checkout/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/paystack/verify/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/portal/portal-client.tsx",import.meta.url),"utf8")]);assert.match(server,/api\.wise\.com\/v1\/rates\?source=USD&target=NGN/);assert.match(server,/amountMinor = Math\.round\(\(baseUsdMinor \/ 100\) \* rate\) \* 100/);assert.match(server,/expiresAt: quotedAt \+ 15 \* 60000/);assert.match(server,/hmacHex\(payload, portalEnv\.SESSION_SECRET\)/);assert.match(checkout,/verifyPaymentQuote/);assert.doesNotMatch(verify,/paymentAmount/);assert.match(client,/Wise rate · no Migrz markup/);assert.match(client,/locked for 15 minutes/);});

test("admin gate provides a working in-place email-code sign-in",async()=>{const [client,css]=await Promise.all([readFile(new URL("../app/admin/admin-client.tsx",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]);assert.match(client,/control@migrzz\.com/);assert.match(client,/\/api\/portal\/auth\/request-code/);assert.match(client,/\/api\/portal\/auth\/verify-code/);assert.match(client,/Email secure code/);assert.match(client,/Verify and open operations/);assert.match(client,/onSwitchAccount/);assert.match(css,/\.admin-signin-form/);});

test("completed reviews notify applicants and unlock a call capped at 60 minutes",async()=>{const [client,adminClient,reviewRoute,portalAppointment,adminAppointment,email,worker,vite,migration,css]=await Promise.all([readFile(new URL("../app/portal/portal-client.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/admin-client.tsx",import.meta.url),"utf8"),readFile(new URL("../app/api/admin/application/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/appointment/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/admin/appointments/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/portal/email.ts",import.meta.url),"utf8"),readFile(new URL("../worker/index.ts",import.meta.url),"utf8"),readFile(new URL("../vite.config.ts",import.meta.url),"utf8"),readFile(new URL("../drizzle/0003_review_notifications_appointments.sql",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]);assert.match(reviewRoute,/reviewCompletedEmail/);assert.match(reviewRoute,/review_notification_sent_at/);assert.match(worker,/processReviewNotificationQueue/);assert.match(vite,/crons: \["\*\/5 \* \* \* \*"\]/);assert.match(email,/Your Migrz assessment review is complete/);assert.match(client,/Book your review call/);assert.match(client,/Calls cannot exceed one hour/);assert.match(portalAppointment,/\[30, 45, 60\]/);assert.match(portalAppointment,/reviewStatus !== "completed"/);assert.match(adminAppointment,/appointment_updated/);assert.match(adminClient,/Appointments/);assert.match(migration,/CHECK\(duration_minutes BETWEEN 15 AND 60\)/);assert.match(css,/\.portal-appointment-form/);});

test("Calendly scheduling, applicant notifications, and completed-call follow-up are durable",async()=>{const [client,calendar,availability,webhook,notifications,adminAppointment,email,worker,migration,cacheMigration,css]=await Promise.all([readFile(new URL("../app/portal/portal-client.tsx",import.meta.url),"utf8"),readFile(new URL("../app/portal/calendly.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/appointment/availability/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/webhooks/calendly/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/notifications/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/admin/appointments/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/portal/email.ts",import.meta.url),"utf8"),readFile(new URL("../worker/index.ts",import.meta.url),"utf8"),readFile(new URL("../drizzle/0004_calendly_call_lifecycle.sql",import.meta.url),"utf8"),readFile(new URL("../drizzle/0006_calendly_resilience.sql",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]);assert.match(calendar,/event_type_available_times/);assert.match(calendar,/resolveCalendlyEventTypeUri/);assert.match(calendar,/ensureCalendlyWebhook/);assert.match(calendar,/migrz-calendly-webhook-v1/);assert.match(calendar,/hostedBookingUrl/);assert.match(availability,/calendlyAvailableTimes/);assert.match(webhook,/calendlyWebhookRequestIsValid/);assert.match(webhook,/provider_booking_url IS NOT NULL/);assert.match(notifications,/FROM notifications WHERE user_id=\?/);assert.match(adminAppointment,/createNotification/);assert.match(adminAppointment,/call_completion_email_sent/);assert.match(email,/Your Migrz review call is complete/);assert.match(worker,/processCallCompletionNotificationQueue/);assert.match(migration,/CREATE TABLE IF NOT EXISTS notifications/);assert.match(cacheMigration,/CREATE TABLE IF NOT EXISTS integration_cache/);assert.match(client,/Join review call/);assert.match(client,/View call details/);assert.match(client,/Choose time in Calendly/);assert.doesNotMatch(client,/Open meeting link/);assert.match(client,/Review next steps/);assert.match(css,/\.portal-live-slots/);});

test("portal operations cover reports, information requests, messaging, reminders, exports and CaseVault handoff",async()=>{const [client,adminOps,portalOps,reportRoute,exportRoute,worker,migration,css]=await Promise.all([readFile(new URL("../app/portal/portal-client.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/operations/operations-client.tsx",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/operations/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/admin/reports/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/export/route.ts",import.meta.url),"utf8"),readFile(new URL("../worker/index.ts",import.meta.url),"utf8"),readFile(new URL("../drizzle/0005_portal_operations.sql",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]);for(const phrase of ["Private messages","Your written assessment","Download my data","CaseVault handoff"])assert.match(client,new RegExp(phrase));for(const phrase of ["Request information","Publish written report","Delivery health","Export complete case"])assert.match(adminOps,new RegExp(phrase));assert.match(portalOps,/information_request/);assert.match(reportRoute,/assessment_report_published/);assert.match(reportRoute,/%PDF-/);assert.match(exportRoute,/migrz-account-export\.json/);assert.match(worker,/processAppointmentReminders/);assert.match(worker,/processNoShowFollowups/);assert.match(worker,/processSlaAlerts/);assert.match(migration,/CREATE TABLE IF NOT EXISTS service_messages/);assert.match(migration,/CREATE TABLE IF NOT EXISTS assessment_reports/);assert.match(migration,/CREATE TABLE IF NOT EXISTS email_deliveries/);assert.match(css,/\.ops-shell/);assert.match(css,/\.portal-inbox-layout/);});

test("P0 to P3 controls are durable, role-gated and private",async()=>{const [platform,account,operations,worker,migration,adminLayout,countries,client]=await Promise.all([readFile(new URL("../app/api/admin/platform/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/portal/account/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/admin/operations/route.ts",import.meta.url),"utf8"),readFile(new URL("../worker/index.ts",import.meta.url),"utf8"),readFile(new URL("../drizzle/0007_operations_grade_portal.sql",import.meta.url),"utf8"),readFile(new URL("../app/admin/layout.tsx",import.meta.url),"utf8"),readFile(new URL("../app/portal/countries.ts",import.meta.url),"utf8"),readFile(new URL("../app/portal/portal-client.tsx",import.meta.url),"utf8")]);for(const feature of ["refund_execute","staff_invite","privacy_complete","casevault_queue","integration_diagnostic_run"])assert.match(platform,new RegExp(feature));assert.match(platform,/requireAdminRole/);for(const feature of ["structured_report","publish_structured_report","information_request_items"])assert.match(operations,new RegExp(feature));for(const table of ["admin_tasks","payment_refunds","structured_reports","consent_records","user_data_requests","security_events","service_feedback"])assert.match(migration,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(worker,/processTrackedEmailRetryQueue/);assert.match(account,/other_sessions_revoked/);assert.match(adminLayout,/index: false/);assert.match(countries,/paypalCountryCodes/);assert.match(client,/Account & privacy/);assert.match(client,/View receipt/);});
