import { activatePayment, json, paypalAccessToken, paypalBaseUrl, portalEnv } from "@/app/portal/server";

export async function POST(request: Request) {
  if (!portalEnv.PAYPAL_WEBHOOK_ID) return json({ error: "Not configured" }, 503); const bodyText = await request.text(); const event = JSON.parse(bodyText) as { id?: string; event_type?: string; resource?: { id?: string; supplementary_data?: { related_ids?: { order_id?: string } }; amount?: { value?: string; currency_code?: string }; status?: string } };
  try { const token = await paypalAccessToken(); const verification = await fetch(`${paypalBaseUrl()}/v1/notifications/verify-webhook-signature`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify({ transmission_id: request.headers.get("paypal-transmission-id"), transmission_time: request.headers.get("paypal-transmission-time"), cert_url: request.headers.get("paypal-cert-url"), auth_algo: request.headers.get("paypal-auth-algo"), transmission_sig: request.headers.get("paypal-transmission-sig"), webhook_id: portalEnv.PAYPAL_WEBHOOK_ID, webhook_event: event }) }); const verified = await verification.json() as { verification_status?: string }; if (!verification.ok || verified.verification_status !== "SUCCESS") return json({ error: "Invalid signature" }, 401); } catch { return json({ error: "Unable to verify signature" }, 401); }
  if (event.event_type !== "PAYMENT.CAPTURE.COMPLETED") return json({ received: true }); const orderId = event.resource?.supplementary_data?.related_ids?.order_id; if (!orderId) return json({ received: true }); const payment = await portalEnv.DB.prepare("SELECT id,amount_minor AS amountMinor,currency FROM payments WHERE provider='paypal' AND provider_reference=? LIMIT 1").bind(orderId).first<{ id: string; amountMinor: number; currency: string }>();
  if (payment) await portalEnv.DB.prepare("INSERT OR IGNORE INTO payment_events (id,payment_id,provider,event_type,provider_event_id,status,detail_json,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(`pe_${crypto.randomUUID()}`, payment.id, "paypal", event.event_type || "unknown", event.id || null, event.resource?.status || "received", JSON.stringify({ orderId }), Date.now()).run().catch(() => undefined);
  if (payment && event.resource?.status === "COMPLETED" && event.resource.amount?.currency_code === payment.currency && Math.round(Number(event.resource.amount.value) * 100) === payment.amountMinor) { await portalEnv.DB.prepare("UPDATE payments SET provider_capture_reference=coalesce(provider_capture_reference,?),receipt_number=coalesce(receipt_number,?) WHERE id=?").bind(event.resource.id || null, `MIGRZ-${payment.id.slice(-10).toUpperCase()}`, payment.id).run(); await activatePayment(payment.id, orderId); } return json({ received: true });
}
