import { audit, json, portalEnv, randomId, requireAdmin } from "@/app/portal/server";
import { reviewCompletedEmail, sendPortalEmail } from "@/app/portal/email";

const reviewStatuses = ["submitted", "in_review", "needs_information", "completed", "closed"] as const;

async function findApplication(publicId: string) {
  return portalEnv.DB.prepare(`SELECT a.id,a.public_id AS publicId,a.status,a.review_status AS reviewStatus,a.current_section AS currentSection,a.answers_json AS answersJson,a.submitted_at AS submittedAt,a.updated_at AS updatedAt,a.admin_updated_at AS adminUpdatedAt,a.review_notification_sent_at AS reviewNotificationSentAt,a.review_due_at AS reviewDueAt,a.report_published_at AS reportPublishedAt,a.casevault_status AS casevaultStatus,a.casevault_reference AS casevaultReference,a.retention_until AS retentionUntil,u.email,u.country_residence AS countryResidence,e.plan,ad.email AS assignedTo FROM applications a JOIN users u ON u.id=a.user_id LEFT JOIN entitlements e ON e.user_id=u.id AND e.status='active' LEFT JOIN admins aa ON aa.id=a.assigned_admin_id LEFT JOIN users ad ON ad.id=aa.user_id WHERE a.public_id=? LIMIT 1`).bind(publicId).first<{ id: string; publicId: string; status: string; reviewStatus: string; currentSection: number; answersJson: string; submittedAt: number | null; updatedAt: number; adminUpdatedAt: number | null; reviewNotificationSentAt: number | null; reviewDueAt: number | null; reportPublishedAt: number | null; casevaultStatus: string; casevaultReference: string | null; retentionUntil: number | null; email: string; countryResidence: string; plan: string | null; assignedTo: string | null }>();
}

export async function GET(request: Request) {
  const session = await requireAdmin(request); if (session.error || !session.user) return session.error!; const publicId = new URL(request.url).searchParams.get("id") || ""; const application = await findApplication(publicId); if (!application) return json({ error: "Application not found" }, 404);
  const [notes, documents, payments, messages, reports, emails, informationItems, structuredReports, tags, tasks] = await Promise.all([
    portalEnv.DB.prepare(`SELECT n.id,n.note,n.created_at AS createdAt,u.email AS authorEmail FROM application_notes n JOIN users u ON u.id=n.admin_user_id WHERE n.application_id=? ORDER BY n.created_at DESC`).bind(application.id).all(),
    portalEnv.DB.prepare(`SELECT id,file_name AS fileName,content_type AS contentType,size,status,created_at AS createdAt FROM documents WHERE application_id=? AND status!='deleted' ORDER BY created_at DESC`).bind(application.id).all(),
    portalEnv.DB.prepare(`SELECT id,plan,provider,amount_minor AS amountMinor,currency,status,provider_reference AS providerReference,created_at AS createdAt,paid_at AS paidAt FROM payments WHERE user_id=(SELECT user_id FROM applications WHERE id=?) ORDER BY created_at DESC`).bind(application.id).all(),
    portalEnv.DB.prepare(`SELECT id,sender_role AS senderRole,kind,subject,body,status,due_at AS dueAt,resolved_at AS resolvedAt,created_at AS createdAt FROM service_messages WHERE application_id=? ORDER BY created_at DESC`).bind(application.id).all(),
    portalEnv.DB.prepare(`SELECT id,version,file_name AS fileName,size,status,summary,created_at AS createdAt,published_at AS publishedAt FROM assessment_reports WHERE application_id=? ORDER BY version DESC`).bind(application.id).all(),
    portalEnv.DB.prepare(`SELECT id,category,recipient,subject,status,attempts,last_error AS lastError,created_at AS createdAt,sent_at AS sentAt FROM email_deliveries WHERE application_id=? ORDER BY created_at DESC LIMIT 50`).bind(application.id).all(),
    portalEnv.DB.prepare(`SELECT id,message_id AS messageId,label,response_type AS responseType,required,status,response_text AS responseText,responded_at AS respondedAt,created_at AS createdAt FROM information_request_items WHERE application_id=? ORDER BY created_at`).bind(application.id).all(),
    portalEnv.DB.prepare(`SELECT id,version,title,executive_summary AS executiveSummary,pathways_json AS pathwaysJson,evidence_gaps_json AS evidenceGapsJson,next_steps_json AS nextStepsJson,status,created_at AS createdAt,updated_at AS updatedAt,published_at AS publishedAt FROM structured_reports WHERE application_id=? ORDER BY version DESC`).bind(application.id).all(),
    portalEnv.DB.prepare(`SELECT tag FROM application_tags WHERE application_id=? ORDER BY tag`).bind(application.id).all(),
    portalEnv.DB.prepare(`SELECT id,title,description,priority,status,due_at AS dueAt,completed_at AS completedAt FROM admin_tasks WHERE application_id=? ORDER BY created_at DESC`).bind(application.id).all(),
  ]);
  await portalEnv.DB.prepare("UPDATE service_messages SET read_by_admin_at=coalesce(read_by_admin_at,?) WHERE application_id=? AND sender_role='applicant'").bind(Date.now(), application.id).run();
  return json({ application: { ...application, answers: JSON.parse(application.answersJson || "{}"), answersJson: undefined }, notes: notes.results, documents: documents.results, payments: payments.results, messages: messages.results, reports: reports.results, emails: emails.results, informationItems: informationItems.results, structuredReports: structuredReports.results.map((item) => ({ ...item, pathways: JSON.parse(String(item.pathwaysJson || "[]")), evidenceGaps: JSON.parse(String(item.evidenceGapsJson || "[]")), nextSteps: JSON.parse(String(item.nextStepsJson || "[]")), pathwaysJson: undefined, evidenceGapsJson: undefined, nextStepsJson: undefined })), tags: tags.results, tasks: tasks.results });
}

export async function PATCH(request: Request) {
  const session = await requireAdmin(request); if (session.error || !session.user) return session.error!; const body = await request.json() as { publicId?: unknown; reviewStatus?: unknown; assignedAdminId?: unknown }; const publicId = typeof body.publicId === "string" ? body.publicId : ""; const application = await findApplication(publicId); if (!application) return json({ error: "Application not found" }, 404); if (typeof body.reviewStatus !== "string" || !reviewStatuses.includes(body.reviewStatus as typeof reviewStatuses[number])) return json({ error: "Invalid review status" }, 400);
  const assignedAdminId = typeof body.assignedAdminId === "string" && body.assignedAdminId ? body.assignedAdminId : null; if (assignedAdminId) { const admin = await portalEnv.DB.prepare("SELECT id FROM admins WHERE id=? AND status='active'").bind(assignedAdminId).first(); if (!admin) return json({ error: "Invalid assignee" }, 400); }
  const now = Date.now(); await portalEnv.DB.prepare("UPDATE applications SET review_status=?,assigned_admin_id=?,admin_updated_at=?,updated_at=? WHERE id=?").bind(body.reviewStatus, assignedAdminId, now, now, application.id).run(); await audit("application_review_updated", "application", application.id, session.user.id, { publicId, reviewStatus: body.reviewStatus, assignedAdminId });
  let notification: "sent" | "queued" | "unchanged" = "unchanged";
  if (body.reviewStatus === "completed" && !application.reviewNotificationSentAt) {
    const claim = await portalEnv.DB.prepare("UPDATE applications SET review_notification_sent_at=-1 WHERE id=? AND review_notification_sent_at IS NULL").bind(application.id).run();
    if (claim.meta.changes) { const answers = JSON.parse(application.answersJson || "{}") as { fullName?: string }; const message = reviewCompletedEmail(application.publicId, answers.fullName || "");
      try { await sendPortalEmail({ token: portalEnv.ZEPTOMAIL_TOKEN, from: portalEnv.ZEPTOMAIL_FROM, fromName: portalEnv.ZEPTOMAIL_FROM_NAME }, application.email, message.subject, message.text, message.html); await portalEnv.DB.prepare("UPDATE applications SET review_notification_sent_at=?,review_notification_attempts=review_notification_attempts+1 WHERE id=?").bind(Date.now(), application.id).run(); await audit("review_completion_email_sent", "application", application.id, session.user.id, { publicId }); notification = "sent"; }
      catch { await portalEnv.DB.prepare("UPDATE applications SET review_notification_sent_at=NULL,review_notification_attempts=review_notification_attempts+1 WHERE id=?").bind(application.id).run(); await audit("review_completion_email_queued", "application", application.id, session.user.id, { publicId }); notification = "queued"; }
    }
  }
  return json({ ok: true, updatedAt: now, notification });
}

export async function POST(request: Request) {
  const session = await requireAdmin(request); if (session.error || !session.user) return session.error!; const body = await request.json() as { publicId?: unknown; note?: unknown }; const publicId = typeof body.publicId === "string" ? body.publicId : ""; const note = typeof body.note === "string" ? body.note.trim().slice(0, 4000) : ""; if (!note) return json({ error: "Write a note before saving" }, 400); const application = await findApplication(publicId); if (!application) return json({ error: "Application not found" }, 404); const noteId = randomId("note_"); await portalEnv.DB.prepare("INSERT INTO application_notes (id,application_id,admin_user_id,note,created_at) VALUES (?,?,?,?,?)").bind(noteId, application.id, session.user.id, note, Date.now()).run(); await audit("application_note_added", "application", application.id, session.user.id, { publicId, noteId }); return json({ ok: true, noteId }, 201);
}
