/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element, react/no-unescaped-entities */
import { ASSESSMENT_URL, faqGroups, pathways, type Pathway } from "./site-data";
import { pathwayCopy } from "./pathway-copy";

const Arrow = () => <span aria-hidden="true">↗</span>;

export function Logo({ light = true }: { light?: boolean }) {
  return <a className={`brand-logo ${light ? "logo-light" : "logo-dark"}`} href="/" aria-label="Migrz home"><img src="/migrz-logo.png" alt="Migrz" /></a>;
}

export function SiteHeader() {
  return <header className="header"><div className="header-inner"><Logo/>
    <nav className="desktop-nav" aria-label="Primary navigation">
      <div className="nav-group"><a href="/#pathways">Pathways</a><div className="mega-menu"><div><span>United States</span><a href="/us/eb-1a">EB-1A</a><a href="/us/niw">National Interest Waiver</a><span>United Kingdom</span><a href="/uk/global-talent-visa">Global Talent Visa</a><a href="/uk/innovator-founder-visa">Innovator Founder</a></div><div><span>Canada</span><a href="/ca/canada-immigration">Canada overview</a><a href="/ca/express-entry">Express Entry</a><a href="/ca/provincial-nominee-program">Provincial Nominee</a><span>More destinations</span><a href="/au/australia-global-talent">Australia</a><a href="/eu/de/germany-eu-blue-card">Germany</a><a href="/uae/dubai-golden-visa">Dubai</a></div></div></div>
      <a href="/process">Process</a><a href="/98-success-rate">Results</a><a href="/customers">Who we help</a>
      <div className="nav-group"><a href="/about">About</a><div className="mini-menu"><a href="/about">Our story</a><a href="/what-makes-us-different">What makes us different</a><a href="/faqs">FAQs</a><a href="https://blog.migrzz.com">Insights</a></div></div>
    </nav>
    <a className="header-cta" href={ASSESSMENT_URL}>Start assessment <Arrow/></a>
    <details className="mobile-menu"><summary aria-label="Open menu"><i/><i/></summary><div className="mobile-panel"><a href="/">Home</a><strong>Pathways</strong>{pathways.map(p=><a key={p.slug} href={`/${p.slug}`}>{p.country} · {p.code}</a>)}<strong>Company</strong><a href="/process">Process</a><a href="/98-success-rate">Results</a><a href="/customers">Who we help</a><a href="/about">About</a><a href="/what-makes-us-different">What makes us different</a><a href="/faqs">FAQs</a><a className="mobile-cta" href={ASSESSMENT_URL}>Start assessment <Arrow/></a></div></details>
  </div></header>;
}

export function SiteFooter() {
  return <footer className="footer"><div className="footer-lead"><Logo/><h2>Exceptional careers deserve more borders, not fewer.</h2><a href={ASSESSMENT_URL}>Start your professional assessment <Arrow/></a></div><div className="footer-grid"><div><span>Pathways</span><a href="/us/eb-1a">US EB-1A</a><a href="/us/niw">US NIW</a><a href="/uk/global-talent-visa">UK Global Talent</a><a href="/ca/canada-immigration">Canada</a><a href="/au/australia-global-talent">Australia</a></div><div><span>Company</span><a href="/about">About Migrz</a><a href="/what-makes-us-different">What makes us different</a><a href="/process">Process</a><a href="/98-success-rate">Results</a><a href="/customers">Who we help</a></div><div><span>Resources</span><a href="/faqs">FAQs</a><a href="https://blog.migrzz.com">Immigration insights</a><a href={ASSESSMENT_URL}>Eligibility assessment</a><a href="https://linkedin.com/company/migrz">LinkedIn</a><a href="https://instagram.com/themigrz">Instagram</a></div><div><span>Office</span><p>2261 Market Street<br/>San Francisco, CA 94114</p><p>Working across the US, UK, Canada, Australia, Germany, and the UAE.</p></div></div><div className="footer-legal"><span>© 2019–2026 Migrz. All rights reserved.</span><p>Migrz is not a law firm and website content is not legal advice. Legal services, where required, are provided by independent attorneys under a separate agreement.</p></div></footer>;
}

function RoutePreview() {
  return <div className="route-preview"><div className="preview-top"><div><span className="micro">Illustrative profile match</span><h3>Your strongest pathways</h3></div><span className="status">Assessment preview</span></div><div className="profile"><span>UA</span><div><b>Product & AI leader</b><small>8 years · 3 markets · 12 evidence signals</small></div></div>{[["01","EB-1A","United States · Extraordinary ability","92"],["02","NIW","United States · National interest","87"],["03","GTV","United Kingdom · Global talent","81"]].map(r=><div className="preview-row" key={r[1]}><small>{r[0]}</small><div><b>{r[1]}</b><span>{r[2]}</span></div><strong>{r[3]}<em>/100</em></strong></div>)}<div className="preview-bottom"><span>Next: evidence review</span><b>Report in 48 hours →</b></div></div>;
}

export function CTA({ title = "Find the route your résumé cannot show you." }: { title?: string }) {
  return <section className="cta-section"><div><span className="eyebrow light">Professional assessment</span><h2>{title}</h2></div><div className="cta-card"><div><b>7+ pathways reviewed</b><span>against your evidence</span></div><div><b>Detailed report</b><span>delivered in 48 hours</span></div><div><b>Expert session</b><span>to explain the strategy</span></div><a href={ASSESSMENT_URL}>Start the paid assessment <Arrow/></a></div></section>;
}

export function HomePage() {
  const featured = pathways.filter(p=>["us/eb-1a","us/niw","uk/global-talent-visa","ca/provincial-nominee-program","au/australia-global-talent","uae/dubai-golden-visa"].includes(p.slug));
  return <>
    <section className="home-hero"><div className="hero-copy"><span className="recommend">The Merit Index · Migrz</span><span className="eyebrow light">Achievement-based immigration, engineered around you</span><h1>Your achievements<br/>are a <em>passport.</em></h1><p>Migrz identifies the permanent-residency pathways your career has already earned, then builds the evidence strategy to move you forward.</p><div className="hero-actions"><a className="btn-accent" href={ASSESSMENT_URL}>Map my pathways <Arrow/></a><a className="link-light" href="/process">How Migrz works →</a></div><div className="hero-checks"><span>Paid professional assessment</span><span>48-hour report</span><span>6 countries</span></div></div><RoutePreview/></section>
    <section className="proof-strip" aria-label="Migrz reported results"><span>Migrz in numbers</span>{[["3,738+","professionals supported"],["6","destination countries"],["14","specialist pathways"],["98%","reported approval rate"]].map(x=><div key={x[1]}><b>{x[0]}</b><small>{x[1]}</small></div>)}</section>
    <section className="intro-section"><span className="eyebrow">The information problem</span><div><h2>You may already qualify for a route you have never considered.</h2><p>High-impact work often looks ordinary from inside your own career. Migrz turns leadership, original contributions, research, recognition, commercial outcomes, and public benefit into an evidence map that immigration decision-makers can evaluate.</p></div></section>
    <section className="pathways-section" id="pathways"><div className="section-head"><div><span className="eyebrow">Pathway index</span><h2>One profile. Several possible futures.</h2></div><p>Compare the route, evidence burden, destination, and long-term outcome before you choose where to build.</p></div><div className="pathway-grid">{featured.map((p,i)=><a className="path-card" href={`/${p.slug}`} key={p.slug}><span>0{i+1} · {p.country}</span><h3>{p.code}</h3><p>{p.summary}</p><b>Explore pathway <Arrow/></b></a>)}</div><a className="all-routes" href="/ca/canada-immigration">Explore all destination routes →</a></section>
    <section className="method-section"><div className="method-copy"><span className="eyebrow light">The Migrz method</span><h2>Strategy before paperwork.</h2><p>The right route is not always the obvious one. Migrz compares first, then commits.</p><a href="/process">See the full process <Arrow/></a></div><div className="method-steps">{[["01","Assess","Review your work, recognition, impact, and existing evidence."],["02","Compare","Model credible routes across countries and identify trade-offs."],["03","Build","Create the evidence architecture and prepare the case."],["04","Manage","Coordinate submission, updates, and any response strategy."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
    <section className="audience-section"><div><span className="eyebrow">Who Migrz is built for</span><h2>Professionals whose work already moves industries.</h2></div><div className="audience-list">{["Technology and AI leaders","Researchers and academics","Healthcare innovators","Finance professionals","Founders and executives","Engineers and specialists"].map((x,i)=><a href="/customers" key={x}><span>0{i+1}</span>{x}<Arrow/></a>)}</div></section>
    <section className="outcomes"><blockquote>“Migrz found evidence other advisers had missed and helped me see my career as a complete immigration case.”</blockquote><div><span>CLIENT OUTCOME</span><b>From scattered achievements to a decision-ready record.</b><a href="/98-success-rate">How Migrz approaches outcomes →</a></div></section>
    <section className="insights"><div className="section-head"><div><span className="eyebrow">Immigration intelligence</span><h2>No fluff. Just useful strategy.</h2></div><a href="https://blog.migrzz.com">Visit the Migrz journal <Arrow/></a></div><div className="insight-grid">{[["Pathways","EB-1A without a PhD","How industry professionals can document extraordinary ability beyond academic credentials."],["Guides","EB-1A self-assessment","A practical framework for understanding the evidence categories before you file."],["Strategy","The immigration priority matrix","How to compare country, career, tax, timing, and long-term outcomes."]].map(x=><a href="https://blog.migrzz.com" key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><b>Read insight <Arrow/></b></a>)}</div></section>
    <CTA/>
  </>;
}

export function PathwayPage({ pathway }: { pathway: Pathway }) {
  const copy = pathwayCopy[pathway.slug];
  return <><section className="page-hero pathway-hero"><div><span className="eyebrow light">{pathway.country} · {pathway.eyebrow}</span><h1>{pathway.title}</h1><p>{pathway.summary}</p><div className="hero-actions"><a className="btn-accent" href={ASSESSMENT_URL}>Start your {pathway.code} assessment <Arrow/></a><a className="link-light" href={pathway.officialUrl}>Read official guidance ↗</a></div></div><div className="pathway-index"><span>{pathway.code}</span><small>{pathway.country}</small><b>{pathway.signal}</b></div></section>
    {pathway.note&&<div className="route-notice"><b>Current-program note</b><p>{pathway.note}</p></div>}
    <section className="definition"><span className="eyebrow">What it is</span><div><h2>{pathway.headline}</h2><p>{pathway.definition}</p><a href={pathway.officialUrl}>{pathway.officialLabel} <Arrow/></a></div></section>
    <section className="route-overview"><div><span className="eyebrow">Understanding the route</span><h2>What this pathway actually asks you to prove.</h2></div><div>{copy.overview.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div></section>
    <section className="route-detail-grid"><article><span className="eyebrow">Eligibility logic</span><h2>The principal requirements</h2><ul>{copy.eligibility.map(item=><li key={item}>{item}</li>)}</ul></article><article><span className="eyebrow">Evidence examples</span><h2>Documents that can carry weight</h2><ul>{copy.evidence.map(item=><li key={item}>{item}</li>)}</ul></article></section>
    <section className="framework"><div className="framework-title"><span className="eyebrow light">The evidence architecture</span><h2>{pathway.frameworkTitle}</h2></div><ol>{pathway.framework.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></li>)}</ol></section>
    <section className="route-detail-grid light-detail"><article><span className="eyebrow">Preparing the case</span><h2>How Migrz structures the work</h2><ol>{copy.preparation.map((item,i)=><li key={item}><b>{String(i+1).padStart(2,"0")}</b><span>{item}</span></li>)}</ol></article><article><span className="eyebrow">Important limitations</span><h2>What applicants should not assume</h2><ul>{copy.cautions.map(item=><li key={item}>{item}</li>)}</ul></article></section>
    <section className="fit-section"><div><span className="eyebrow">Who may fit</span><h2>Built for credible, documentable impact.</h2><ul>{pathway.candidates.map(x=><li key={x}>{x}</li>)}</ul></div><div className="benefit-card"><span>Route characteristics</span>{pathway.benefits.map(x=><p key={x}>✓ {x}</p>)}<small>Eligibility, timing, fees, and government requirements can change. The assessment confirms the current rules for your case.</small></div></section>
    <section className="process-teaser"><span className="eyebrow">From profile to petition</span><h2>Assessment. Strategy. Evidence. Execution.</h2><div>{["Professional assessment","Route and evidence plan","Application preparation","Submission and case management"].map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div><a href="/process">See the complete Migrz process <Arrow/></a></section><CTA title={`Find out whether ${pathway.code} fits your record.`}/></>;
}

export function AboutPage() {
  return <><PageHero eyebrow="About Migrz" title="We do not take every case. We take cases we can build responsibly." text="Since 2019, Migrz has focused on achievement-based pathways for professionals whose impact deserves to travel."/><section className="story"><span className="eyebrow">Our story</span><div><h2>It started with frustration.</h2><p>Migrz began after its founders helped navigate an EB-1A process while watching brilliant professionals accept career limitations they did not need to accept.</p><p>The pathways existed. Many people simply did not know about them, and generalist advisers often missed the evidence that separated a viable case from a weak one.</p><h3>So Migrz chose one focus.</h3><p>Help exceptional professionals pursue permanent residency through achievement-based and high-skill pathways. Not tourist visas. Not student visas. Not every immigration matter.</p></div></section><Values/><section className="specialization"><div><span className="eyebrow light">Specialization</span><h2>What Migrz handles</h2></div><div>{pathways.slice(0,10).map(p=><a key={p.slug} href={`/${p.slug}`}><span>{p.country}</span><b>{p.title}</b><Arrow/></a>)}</div></section><CTA/></>;
}

function Values(){ return <section className="values"><div className="section-head"><div><span className="eyebrow">What Migrz believes</span><h2>Your achievements are your pathway.</h2></div><p>Many professionals do not have a qualification problem. They have an information and evidence problem.</p></div><div>{[["01","Achievements come first","Your real work and measurable impact are the starting point."],["02","Quality over volume","A selective case model protects clients and the integrity of the work."],["03","Execution over theory","Criteria matter only when they are translated into coherent evidence."],["04","Honesty over popularity","A responsible assessment can recommend waiting, changing route, or not filing."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>; }

export function DifferencePage(){ return <><PageHero eyebrow="What makes Migrz different" title="Not better at everything. Different by design." text="Migrz is built around specialization, selective engagement, evidence strategy, and transparent case decisions."/><section className="comparison"><div className="comparison-head"><span className="eyebrow">The operating model</span><h2>Generalist volume vs. specialist outcomes.</h2></div>{[["Focus","Many visa categories","Achievement-based and high-skill pathways"],["Assessment","A sales consultation","A paid, written evidence and route analysis"],["Case acceptance","Take most paying applicants","Decline cases Migrz cannot responsibly build"],["Strategy","Choose a country first","Compare credible routes before committing"],["Evidence","Collect documents","Build a decision-ready narrative from impact"],["Transparency","Opaque scope and pricing","Clear assessment scope, route logic, and next steps"]].map((x,i)=><div className="compare-row" key={x[0]}><span>0{i+1} · {x[0]}</span><p>{x[1]}</p><strong>{x[2]}</strong></div>)}</section><Values/><section className="selective"><div><span className="eyebrow light">Selective by design</span><h2>Migrz says “not yet” when that is the responsible answer.</h2></div><ul><li>The current evidence does not support the route.</li><li>The expected timeline is not realistic.</li><li>Another route or provider is a better fit.</li><li>The applicant is not ready to follow the evidence process.</li></ul></section><CTA title="Experience the difference in the first 48 hours."/></> }

export function ProcessPage(){ const steps=[["01","Professional assessment","Migrz reviews your profile across relevant pathways, maps the evidence, identifies gaps, and delivers a written report. The current listed assessment price is $350."],["02","Strategic planning","If a route is viable, the team defines the country, pathway, evidence architecture, timeline, responsibilities, and engagement scope."],["03","Application preparation","Documents are collected, evidence is developed and organized, recommendation material is coordinated, and the application narrative is prepared for review."],["04","Submission and case management","The filing is coordinated with the relevant legal or professional provider, status is tracked, and any government request is addressed within the agreed scope."]]; return <><PageHero eyebrow="The Migrz process" title="Clarity at every consequential step." text="From a paid assessment to submission and case management, every stage should answer one question: what happens next?"/><section className="process-list">{steps.map(x=><article key={x[0]}><span>{x[0]}</span><div><h2>{x[1]}</h2><p>{x[2]}</p></div></article>)}</section><section className="process-principle"><p>40% of Migrz's reported successful cases were previously rejected elsewhere.</p><h2>Same qualifications. Different evidence strategy.</h2></section><CTA/></> }

export function ResultsPage(){ return <><PageHero eyebrow="Reported outcomes" title="Migrz does not promise certainty. It shows its work." text="The current site reports a 98% approval rate. The new site presents that claim with the method, limits, and context it needs."/><section className="results-grid">{[["98%","reported approval rate"],["3,738+","professionals supported"],["6","destination countries"],["23","professions represented"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section><section className="results-explain"><div><span className="eyebrow">What the number means</span><h2>Selection is part of the method.</h2></div><div><p>Migrz attributes its reported approval rate to narrow specialization, paid assessment, declining cases that are not ready, building evidence before filing, and managing the response process.</p><p>A historical approval rate is not a guarantee. Government decisions, policy changes, applicant evidence, and case-specific facts remain outside any consultant's control.</p><a href="/what-makes-us-different">See what makes Migrz different <Arrow/></a></div></section><section className="receipts"><span className="eyebrow light">The standard</span><h2>Approval received. Client relocated. Life transformed.</h2><p>Success is more than a filed application. It is a strategy that remains useful through the decision and the move that follows.</p></section><CTA title="Start with an assessment, not a promise."/></> }

export function CustomersPage(){ const groups=[["Technology","Software engineers, data scientists, CTOs, product leaders, and AI specialists building systems at scale."],["Healthcare","Doctors, researchers, founders, and practitioners advancing medical outcomes and access."],["Finance","Investment professionals, fintech builders, risk leaders, and strategists shaping financial systems."],["Research and academia","PhD holders, published researchers, principal investigators, and thought leaders advancing their fields."],["Engineering","Technical specialists and engineering leaders delivering infrastructure, products, energy, and industrial systems."],["Business and entrepreneurship","Founders, executives, and operators creating companies, jobs, revenue, and economic impact."]]; return <><PageHero eyebrow="Who Migrz helps" title="Exceptional professionals with documentable impact." text="Migrz works best with people who have depth in their field, evidence of contribution, and the patience to build a rigorous case."/><section className="customer-grid">{groups.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h2>{x[0]}</h2><p>{x[1]}</p></article>)}</section><section className="fit-check"><div><span className="eyebrow light">A strong working fit</span><h2>You bring the record. Migrz brings the structure.</h2></div><ul><li>Five or more years of meaningful professional experience</li><li>Measurable impact beyond a job description</li><li>A need for permanent residency or long-term mobility</li><li>Respect for a documented, collaborative process</li><li>Willingness to invest in professional assessment and execution</li></ul></section><CTA/></> }

export function FAQPage(){ return <><PageHero eyebrow="FAQ center" title="Clear answers before a consequential decision." text="Start with what Migrz does, what it does not do, and what you should expect from the assessment."/><section className="faq-section">{faqGroups.map(group=><div className="faq-group" key={group.title}><h2>{group.title}</h2><div>{group.items.map(item=><details key={item[0]}><summary>{item[0]}<span>+</span></summary><p>{item[1]}</p></details>)}</div></div>)}</section><CTA title="Still deciding? Start with the assessment scope."/></> }

function PageHero({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <section className="page-hero"><div><span className="eyebrow light">{eyebrow}</span><h1>{title}</h1><p>{text}</p><a className="btn-accent" href={ASSESSMENT_URL}>Start professional assessment <Arrow/></a></div><div className="hero-monogram"><span>M</span><small>MERIT<br/>MOBILITY<br/>MIGRZ</small></div></section>}

export function ContentPage({slug}:{slug:string}){ if(slug==="about")return <AboutPage/>; if(slug==="what-makes-us-different")return <DifferencePage/>; if(slug==="process")return <ProcessPage/>; if(slug==="98-success-rate")return <ResultsPage/>; if(slug==="customers")return <CustomersPage/>; if(slug==="faqs")return <FAQPage/>; return null; }
