/* eslint-disable @next/next/no-html-link-for-pages, react/no-unescaped-entities */

import { ASSESSMENT_URL } from "./site-data";

function Arrow(){return <span className="brand-arrow" aria-hidden="true">→</span>}

function TrustHero({eyebrow,title,text}:{eyebrow:string;title:string;text:string}) {
  return <section className="trust-hero"><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></section>;
}

const clients = [
  {person:"Dr. Chinwe A.",role:"Healthcare professional",move:"Now in Texas",route:"EB-1A",result:"Approved in seven months",quote:"I was told by two immigration lawyers I needed more publications. Migrz found 11 pieces of evidence they completely missed. EB-1A approved in 7 months.",lesson:"A serious assessment looks beyond publication counts and tests the complete record against every relevant evidence category."},
  {person:"Ibrahim K.",role:"Software architect",move:"Now in California",route:"National Interest Waiver",result:"Reported approval after a route change",quote:"Lost a $260K CTO position due to visa issues. Three months later, permanent US resident through NIW. Migrz saw pathways I didn't know existed.",lesson:"The best-known pathway is not always the strongest one. Comparing routes before filing can change the strategy materially."},
  {person:"Alex P.",role:"Fintech founder",move:"Now in Dubai",route:"UAE Golden Visa",result:"Reported decision in 14 days",quote:"14 days. That's how long my Dubai Golden Visa took. After 2 years fighting for US EB-1A, I had 10-year UAE residency in two weeks.",lesson:"Destination strategy matters. A credible alternative can better match the applicant's immediate business and mobility goals."},
];

export function CaseStudiesPage(){return <><TrustHero eyebrow="Published client outcomes" title="Real decisions begin with the right diagnosis." text="These privacy-protected snapshots reproduce outcomes and quotations previously published by Migrz. They illustrate individual experiences, not a promise that another applicant will receive the same result."/><section className="case-library">{clients.map((client,index)=><article key={client.person}><div className="case-number">0{index+1}</div><div className="case-summary"><span>{client.route}</span><h2>{client.role}</h2><p>{client.move}</p><b>{client.result}</b></div><div className="case-narrative"><blockquote>“{client.quote}”</blockquote><strong>{client.person}</strong><h3>Why this case matters</h3><p>{client.lesson}</p></div></article>)}</section><section className="proof-disclosure"><div><span>Evidence standard</span><h2>A client story is context, not probability.</h2></div><div><p>Names are shortened for privacy. These snapshots are based on Migrz-published accounts and have not been converted into invented timelines, documents, or legal facts. A future proof release should add redacted decision notices only with client permission and a documented verification process.</p><a href="/98-success-rate">Read the outcomes methodology <Arrow/></a></div></section></>}

export function TeamPage(){return <><TrustHero eyebrow="The people behind the strategy" title="Senior judgment should have names attached to it." text="Migrz describes a founder-led model. Clients should know who directs assessment, evidence strategy, operations, and any independent legal work before an engagement begins."/><section className="team-grid"><article><div className="team-mark">UA</div><span>CEO &amp; Co-Founder</span><h2>Uchechukwu Ajuzieogu</h2><p>Leads Migrz's strategic direction and public education on achievement-based immigration, evidence positioning, and professional mobility. Migrz's public materials describe his perspective as informed by navigating the EB-1A process and working across research, technology, and policy.</p><a href="https://www.linkedin.com/company/migrz">View Migrz on LinkedIn <Arrow/></a></article><article><div className="team-mark">MN</div><span>COO &amp; Co-Founder</span><h2>Maryangel Nnamdi</h2><p>Leads operations and the systems that move a client from assessment through preparation and case coordination. Migrz's public materials identify her as a co-founder focused on operational delivery and immigration systems.</p><a href="https://www.linkedin.com/company/migrz">View Migrz on LinkedIn <Arrow/></a></article></section><section className="role-boundaries"><div><span>Accountability map</span><h2>Who does what should be written down.</h2></div><div>{[["Assessment and pathway strategy","Migrz reviews the career record, compares relevant routes, identifies evidence gaps, and explains the recommended strategy."],["Case operations","Migrz coordinates the agreed evidence plan, responsibilities, document workflow, communication, and known milestones."],["Independent legal services","Where legal advice or representation is required, it is provided by an appropriately engaged independent attorney under the applicable agreement."],["Government decision","Only the relevant immigration authority controls eligibility findings, requests, processing, and final decisions."]].map(item=><article key={item[0]}><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div></section></>}

export function AssessmentPage(){return <><TrustHero eyebrow="Paid professional assessment · $350" title="Buy clarity before you buy a full case." text="The Migrz assessment is a standalone professional service: a structured review of your record, comparison of credible pathways, written findings, and an expert consultation—not a free sales call."/><section className="assessment-offer"><div><span>What you receive</span><h2>A decision you can use, even when the answer is “not yet.”</h2><p>The assessment is designed to distinguish a viable route from an expensive assumption. Migrz may recommend proceeding, changing country or pathway, building evidence for a defined period, or not filing.</p><a className="btn-accent" href={ASSESSMENT_URL}>Begin the secure assessment <Arrow/></a></div><div className="assessment-list">{[["01","Cross-route review","Your education, work, leadership, recognition, original contributions, remuneration, publications, judging, awards, and future plans are considered across relevant destinations."],["02","Written eligibility report","You receive the route recommendation, reasoning, strongest evidence, material gaps, major risks, and a practical next-step plan."],["03","Expert consultation","A consultation is included so you can question the findings, understand trade-offs, and decide whether any larger engagement makes sense."],["04","48-hour target","Migrz currently targets report delivery within 48 hours after the requested information and evidence have been received." ]].map(item=><article key={item[0]}><span>{item[0]}</span><div><h3>{item[1]}</h3><p>{item[2]}</p></div></article>)}</div></section><section className="assessment-boundaries"><h2>Before you pay</h2><div><p><strong>Price:</strong> The currently published assessment price is $350. Confirm the amount and currency presented at checkout.</p><p><strong>Not an approval guarantee:</strong> The service assesses evidence and strategy. It cannot determine how a government authority will decide.</p><p><strong>Full-service fees:</strong> Petition preparation or other continuing services are separate and should be described in a written scope before engagement.</p><p><strong>Refunds and cancellations:</strong> Review the checkout and engagement terms that apply before payment. Do not rely on assumptions not stated in writing.</p></div></section></>}

const legalSections:Record<string,{eyebrow:string;title:string;intro:string;sections:Array<[string,string]>}>={
  privacy:{eyebrow:"Privacy notice",title:"Your information deserves a clear boundary.",intro:"This notice explains the information Migrz receives through this website, the assessment journey, and measurement tools, together with the choices available to visitors.",sections:[["Information you provide","Migrz may receive identity and contact details, professional history, education, immigration goals, family or destination preferences, payment-related confirmation, documents, and communications that you choose to submit through an assessment or engagement."],["Website measurement","With your permission, the site uses Google Analytics, Microsoft Clarity, and Meta Pixel to understand visits, interactions, and assessment interest. You can accept or decline optional analytics and reopen Cookie settings from the footer."],["How information is used","Information may be used to respond to enquiries, deliver an assessment, evaluate potential pathways, administer an engagement, protect the service, understand site performance, and meet applicable operational or legal obligations."],["Sharing and professional services","Information may be shared with providers that support hosting, forms, payments, communications, analytics, and case operations. Where an independent attorney is engaged, the applicable agreement should explain the attorney's role and handling of information."],["Retention and security","Migrz should retain information only for an appropriate operational, contractual, security, or legal period. No internet service can promise absolute security; sensitive records should be submitted only through an approved channel."],["Your choices","Depending on location and applicable law, you may have rights concerning access, correction, deletion, restriction, objection, or withdrawal of consent. Use the communication channel supplied in your assessment or engagement, or write to the postal address below." ]]},
  terms:{eyebrow:"Website terms",title:"Clear expectations before consequential work.",intro:"These terms govern use of the public Migrz website. Any paid assessment, case-preparation service, or independent legal service may also be governed by checkout disclosures and a separate written agreement.",sections:[["Educational information","Website material is general information and is not legal advice, a legal opinion, or a substitute for advice about a particular person's facts."],["No guarantee","Eligibility, processing, and final decisions are controlled by government authorities. Past outcomes, examples, timelines, or reported approval rates do not guarantee a future result."],["Accuracy and change","Immigration programs, fees, thresholds, forms, and processing practices can change. Migrz aims to link to official sources, but visitors must confirm current requirements before acting."],["Paid services","The scope, price, deliverables, responsibilities, timing, cancellation terms, and refund terms for an assessment or continuing service are those shown at checkout or in the applicable written agreement."],["Responsible use","Visitors must not misuse the site, interfere with its operation, submit unlawful or misleading material, impersonate another person, or attempt unauthorized access."],["Intellectual property","The Migrz brand, original site design, copy, and materials are protected to the extent provided by applicable law. Government forms and third-party materials remain the property of their respective owners." ]]},
  "cookie-policy":{eyebrow:"Cookie policy",title:"Measurement should be a choice, not a surprise.",intro:"Migrz uses a small preference record for essential functionality and, only when permitted, optional measurement technologies.",sections:[["Necessary preference","The site stores your analytics choice under the name migrz_analytics_consent so it can respect the selection on later visits."],["Google Analytics","Google Analytics helps measure visits, page use, and assessment-link activity. Cross-domain configuration may help preserve campaign context between migrzz.com and apply.migrzz.com when both properties are correctly instrumented."],["Microsoft Clarity","Clarity can provide aggregated interaction and session-quality information that helps identify confusing layouts or broken journeys."],["Meta Pixel","Meta Pixel can help measure whether advertising leads to visits or assessment interest and support campaign reporting."],["Changing your choice","Choose Cookie settings in the footer at any time. Declining optional analytics does not block the public site or assessment links." ]]},
  accessibility:{eyebrow:"Accessibility statement",title:"Serious guidance should be usable by more people.",intro:"Migrz aims to make its public website understandable and operable across modern devices, keyboard navigation, zoom, and assistive technologies.",sections:[["Current measures","The site includes semantic headings, keyboard-focus indicators, a skip link, reduced-motion support, descriptive destination images, responsive layouts, and touch-sized mobile navigation."],["Assessment experience","The assessment runs on a separate Migrz subdomain. Migrz should review that experience independently for labels, errors, instructions, keyboard access, focus order, and mobile reflow."],["Known limitations","Automated checks do not prove full conformance. Immigration documents, third-party pages, embedded tools, and future content may introduce issues that require human testing."],["Feedback","If a barrier prevents access, provide the page, device, assistive technology, and a description through an existing Migrz communication channel or by post so the issue can be investigated." ]]},
  disclaimer:{eyebrow:"Professional disclaimer",title:"Strategy is not certainty.",intro:"Migrz helps clients understand pathways and organize evidence. It does not control immigration law, government processing, or adjudication.",sections:[["Not a law firm","Migrz states that it is not a law firm. Legal services, where required, are provided by independent attorneys under separate agreements."],["No attorney-client relationship from browsing","Using this website, reading its content, or submitting an initial assessment does not by itself create an attorney-client relationship."],["No guaranteed result","No pathway, assessment result, case study, testimonial, timeline, or historical performance figure guarantees eligibility or approval."],["Official requirements prevail","Visitors should rely on the current rules and instructions of the relevant immigration authority and obtain qualified legal advice where appropriate."],["Individual facts matter","Two professionals with similar titles may receive different advice because evidence, timing, nationality-related procedures, family circumstances, destination goals, and government rules differ." ]]},
};

export function LegalPage({slug}:{slug:string}){const page=legalSections[slug];if(!page)return null;return <><TrustHero eyebrow={page.eyebrow} title={page.title} text={page.intro}/><section className="legal-page"><div className="legal-meta"><span>Effective 22 August 2026</span><p>Migrz<br/>2261 Market Street<br/>San Francisco, CA 94114</p></div><div>{page.sections.map(section=><article key={section[0]}><h2>{section[0]}</h2><p>{section[1]}</p></article>)}</div></section></>}

export function TrustPage({slug}:{slug:string}){if(slug==="case-studies")return <CaseStudiesPage/>;if(slug==="team")return <TeamPage/>;if(slug==="assessment")return <AssessmentPage/>;return <LegalPage slug={slug}/>}
