"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Platform = { integrations: Record<string, boolean>; paypalDiagnostic: null | { configured: boolean; mode: string; authenticated: boolean; error?: string }; tasks: Array<{ id: string; title: string; priority: string; status: string; dueAt: number | null; applicationPublicId: string | null; assignedTo: string | null }>; refunds: Array<{ id: string; amountMinor: number; status: string; provider: string; currency: string; email: string; reason: string }>; privacy: Array<{ id: string; requestType: string; status: string; email: string; requestedAt: number }>; feedback: Array<{ id: string; stage: string; rating: number; comment: string; email: string; applicationPublicId: string }>; handoffs: Array<{ id: string; provider: string; status: string; applicationPublicId: string; externalReference: string | null; lastError: string | null }>; failedEmails: Array<{ id: string; recipient: string; subject: string; attempts: number; lastError: string | null }>; security: Array<{ id: string; event: string; email: string | null; createdAt: number }>; staff: Array<{ id: string; email: string; role: string; status: string; lastLoginAt: number | null }>; funnel: { accounts: number; paid: number; submitted: number; completed: number; calls: number } };

const stamp = (value: number | null) => value ? new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "Not set";
export function PlatformClient() {
  const [data, setData] = useState<Platform | null>(null); const [notice, setNotice] = useState("Checking secure access…"); const [busy, setBusy] = useState(false); const [task, setTask] = useState(""); const [staffEmail, setStaffEmail] = useState(""); const [staffRole, setStaffRole] = useState("reviewer");
  const load = useCallback(async (diagnostics = false) => { const response = await fetch(`/api/admin/platform${diagnostics ? "?diagnostics=1" : ""}`, { cache: "no-store" }); const body = await response.json() as Platform & { error?: string }; if (!response.ok) { setNotice(body.error || "Administrator access required."); return; } setData(body); setNotice(""); }, []);
  // The first protected platform read resolves into the dashboard state.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const act = async (action: string, payload: Record<string, unknown> = {}) => { setBusy(true); setNotice(""); const response = await fetch("/api/admin/platform", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const body = await response.json() as { error?: string }; setBusy(false); if (!response.ok) return setNotice(body.error || "Operation failed."); setNotice("Change saved and added to the audit trail."); await load(); };
  if (!data) return <main className="admin-access"><Image src="/migrz-logo.png" alt="Migrz" width={443} height={84} /><h1>{notice}</h1><Link href="/admin">Return to admin sign-in →</Link></main>;
  return <div className="platform-shell"><header><Link href="/admin"><Image src="/migrz-logo.png" alt="Migrz" width={443} height={84} /></Link><div><strong>Platform control</strong><Link href="/admin">Operations dashboard</Link><Link href="/admin/operations">Case workspace</Link></div></header><main><section className="platform-heading"><div><span className="portal-eyebrow">P0–P3 operations layer</span><h1>Control the service, not just the cases.</h1><p>Payments, team access, privacy, integrations, delivery failures and internal work are managed here with an audit trail.</p></div><button disabled={busy} onClick={() => void load(true)}>Run live integration checks</button></section>{notice && <p className="ops-notice" role="status">{notice}</p>}
  <section className="platform-funnel">{Object.entries(data.funnel).map(([key,value]) => <article key={key}><span>{key}</span><strong>{value}</strong></article>)}</section>
  <div className="platform-grid"><section><h2>Integration health</h2><div className="platform-health">{Object.entries(data.integrations).map(([key,value]) => <p key={key}><span className={value ? "is-on" : "is-off"} />{key}<strong>{value ? "Configured" : "Missing"}</strong></p>)}</div>{data.paypalDiagnostic && <article className={`platform-diagnostic ${data.paypalDiagnostic.authenticated ? "is-pass" : "is-fail"}`}><strong>PayPal {data.paypalDiagnostic.mode} OAuth</strong><span>{data.paypalDiagnostic.authenticated ? "Authenticated successfully" : data.paypalDiagnostic.error || "Failed"}</span></article>}<small>A configured provider is not marked authenticated until its protected live check succeeds.</small></section>
  <section><h2>Internal work queue</h2><label>New task<input value={task} onChange={(event) => setTask(event.target.value)} placeholder="Follow up on missing evidence" /></label><button disabled={busy || !task.trim()} onClick={() => { void act("task_create", { title: task }); setTask(""); }}>Create my task</button><div className="platform-list">{data.tasks.map((item) => <article key={item.id}><div><strong>{item.title}</strong><small>{item.priority} · {item.applicationPublicId || "General"} · {stamp(item.dueAt)}</small></div><button disabled={busy || item.status === "completed"} onClick={() => void act("task_update", { id: item.id, status: "completed" })}>{item.status === "completed" ? "Done" : "Complete"}</button></article>)}</div></section>
  <section><h2>Staff & roles</h2><div className="platform-inline"><input type="email" value={staffEmail} onChange={(event) => setStaffEmail(event.target.value)} placeholder="verified staff email" /><select value={staffRole} onChange={(event) => setStaffRole(event.target.value)}>{["reviewer","caseworker","finance","support","superadmin"].map((role) => <option key={role}>{role}</option>)}</select><button disabled={busy || !staffEmail} onClick={() => void act("staff_invite", { email: staffEmail, role: staffRole })}>Add</button></div><div className="platform-list">{data.staff.map((item) => <article key={item.id}><div><strong>{item.email}</strong><small>{item.role} · {item.status} · last login {stamp(item.lastLoginAt)}</small></div></article>)}</div></section>
  <section><h2>Privacy requests</h2><div className="platform-list">{data.privacy.length ? data.privacy.map((item) => <article key={item.id}><div><strong>{item.requestType} · {item.email}</strong><small>{item.status} · requested {stamp(item.requestedAt)}</small></div><button disabled={busy || item.status === "completed"} onClick={() => void act("privacy_complete", { id: item.id, adminNote: "Completed through Migrz platform control." })}>Complete</button></article>) : <p>No open data requests.</p>}</div></section>
  <section><h2>Refund control</h2><div className="platform-list">{data.refunds.length ? data.refunds.map((item) => <article key={item.id}><div><strong>{item.email} · {(item.amountMinor / 100).toFixed(2)} {item.currency}</strong><small>{item.provider} · {item.status} · {item.reason}</small></div>{item.status === "requested" && <button disabled={busy} onClick={() => void act("refund_execute", { id: item.id })}>Issue refund</button>}</article>) : <p>No refund requests.</p>}</div></section>
  <section><h2>CaseVault handoffs</h2><div className="platform-list">{data.handoffs.length ? data.handoffs.map((item) => <article key={item.id}><div><strong>{item.applicationPublicId}</strong><small>{item.provider} · {item.status} · {item.externalReference || "Awaiting reference"}{item.lastError ? ` · ${item.lastError}` : ""}</small></div></article>) : <p>No queued integration handoffs.</p>}</div></section>
  <section><h2>Applicant feedback</h2><div className="platform-list">{data.feedback.length ? data.feedback.map((item) => <article key={item.id}><div><strong>{"★".repeat(item.rating)} · {item.email}</strong><small>{item.stage} · {item.applicationPublicId}</small><p>{item.comment}</p></div></article>) : <p>No feedback yet.</p>}</div></section>
  <section><h2>Exceptions</h2><div className="platform-list">{data.failedEmails.map((item) => <article key={item.id}><div><strong>Email · {item.recipient}</strong><small>{item.subject} · {item.attempts} attempts · {item.lastError || "unknown error"}</small></div></article>)}{data.security.map((item) => <article key={item.id}><div><strong>Security · {item.event}</strong><small>{item.email || "anonymous"} · {stamp(item.createdAt)}</small></div></article>)}{!data.failedEmails.length && !data.security.length && <p>No current delivery or security exceptions.</p>}</div></section></div></main></div>;
}
