import { json, portalEnv, requireSession } from "@/app/portal/server";

export async function GET(request: Request) {
  const session = await requireSession(request, true); if (session.error || !session.user) return session.error!;
  const payment = await portalEnv.DB.prepare("SELECT id,plan,provider,amount_minor AS amountMinor,currency,status,provider_reference AS providerReference,receipt_number AS receiptNumber,paid_at AS paidAt FROM payments WHERE user_id=? AND status IN ('paid','refunded') ORDER BY paid_at DESC LIMIT 1").bind(session.user.id).first<{ id: string; plan: string; provider: string; amountMinor: number; currency: string; status: string; providerReference: string; receiptNumber: string | null; paidAt: number }>();
  if (!payment) return json({ error: "Paid receipt not found." }, 404);
  const amount = new Intl.NumberFormat(payment.currency === "NGN" ? "en-NG" : "en-US", { style: "currency", currency: payment.currency }).format(payment.amountMinor / 100); const receipt = payment.receiptNumber || `MZ-RCPT-${payment.id.slice(-10).toUpperCase()}`;
  const escape = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character] || character));
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(receipt)} · Migrz receipt</title><style>body{font:15px Arial,sans-serif;color:#10233f;margin:0;background:#f3f5f7}.sheet{max-width:720px;margin:50px auto;background:white;padding:50px;border:1px solid #dbe1e7}.brand{font-size:30px;font-weight:900;letter-spacing:.08em}.paid{display:inline-block;padding:7px 10px;background:#e0f0e5;color:#28613c;border-radius:30px;text-transform:uppercase;font-weight:800;font-size:11px}h1{font-size:44px;margin:45px 0 8px}dl{margin:35px 0}dl div{display:flex;justify-content:space-between;padding:15px 0;border-top:1px solid #e4e8ec}dt{color:#6a7888}dd{font-weight:700;text-align:right}.amount{font-size:30px}.legal{margin-top:45px;color:#6a7888;line-height:1.6}@media print{body{background:#fff}.sheet{border:0;margin:0;max-width:none}}</style></head><body><main class="sheet"><div class="brand">MIGRZ</div><h1>Payment receipt</h1><p class="paid">${escape(payment.status)}</p><dl><div><dt>Receipt</dt><dd>${escape(receipt)}</dd></div><div><dt>Account</dt><dd>${escape(session.user.email)}</dd></div><div><dt>Assessment</dt><dd>${escape(payment.plan)}</dd></div><div><dt>Provider</dt><dd>${escape(payment.provider)}</dd></div><div><dt>Provider reference</dt><dd>${escape(payment.providerReference)}</dd></div><div><dt>Paid</dt><dd>${new Date(payment.paidAt).toUTCString()}</dd></div><div><dt>Total</dt><dd class="amount">${escape(amount)}</dd></div></dl><p class="legal">This receipt confirms assessment access. It is not an immigration approval, eligibility decision, or government fee receipt. Print or save this page as PDF for your records.</p></main></body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "content-disposition": `inline; filename="${receipt}.html"`, "cache-control": "private, no-store", "x-frame-options": "DENY" } });
}
